### ISSUE TITLE
sshfs works fine, sshfs.r does not

### ISSUE THREAD

**Issue by burgerga** [billziss-gh/sshfs-win#102]
I'm trying to mount the root folder, but 

```
net use X: \\sshfs.r\host 
```

fails with 

```
System error 67 has occurred.

The network name cannot be found.
```

However, the workaround

```
net use X: \\sshfs\host\..\.. 
```

seems to work fine.

**Comment by billziss-gh** [comment]
This should only work with latest beta. Have you found otherwise?

**Comment by burgerga** [comment]
Ah, I didn't know. Just installed it with choco. Will try again in the future! Thanks ;)
