### ISSUE TITLE
How Can I Mount a Specific Drive in Windows Hosts that Run OpenSSH Server Feature?

### ISSUE THREAD

**Issue by falhumai96** [billziss-gh/sshfs-win#103]
I was able to mount the root of the C drive, but not any other drives (or maybe I do not know the syntax for mounting certain drives in Windows hosts). How would I achieve specific Windows drives, if it is possible?

**Comment by billziss-gh** [comment]
In general the [SSHFS](https://github.com/libfuse/sshfs) syntax for connecting to an SSH server is `[user@]host:[dir]`. In SSHFS-Win the corresponding syntax is `\\sshfs\[user@]host[\dir]`.

So if you know how you would connect to a Windows host drive using normal SSHFS (or SCP) you should be able to figure out the syntax to use with SSHFS-Win.

**Comment by falhumai96** [comment]
I apologize. This issue turned out to be not an SSHFS-Win issue. Though, for future reference, I was able to get around the issue and mounted a specific drive on Windows by not using the default OpenSSH server found on the optional features of Windows, but rather using a Cygwin's (or MSYS2's) SSH server, as the bash in Cygwin (or MSYS2) can access different drives as a mounted folder rather than a drive (for e.g. drive "Z:" in Windows is visible in Cygwin's bash as "/cygdrive/z"). Therefore, you can mount that specific folder for the remote drive using SSHFS-Win.

**Comment by billziss-gh** [comment]
@falhumai96 no problem. I am glad your problem was resolved!
