### ISSUE TITLE
Disconnects shortly after successfully connecting and mounting

### ISSUE THREAD

**Issue by narfanar** [billziss-gh/sshfs-win#107]
Followed this: http://makerlab.cs.hku.hk/index.php/en/mapping-network-drive-over-ssh-in-windows

Connect, auth, mount.

See mounted drive in Computer.

Browser or do whatever.

In a minute or two, the drive disappears from the main window. Clicking it in the navigation bar says it's "unavailable". Similar failure at accessing anything under it by any other program.

**Comment by billziss-gh** [comment]
- What version of SSHFS-Win, WinFsp and Windows are you using?
- What does the UNC syntax for your mounted storage looks like?

**Comment by narfanar** [comment]
Using beta for both works fine as far as I can tell :D
