### ISSUE TITLE
Automatically reconnect on remote available

### ISSUE THREAD

**Issue by narfanar** [billziss-gh/sshfs-win#108]
This does not happen currently.

Using latest of SSHFS-Win and its backend.

Network hiccup causes the mounted drive to disappear but it's still "bound" to the remote user and IP in the "Map network drive..." option in Explorer.

This means that every time the network does anything untowards, I have to remove the mounted drive from command line and remount it, which can get pretty annoying with spotty internet.

**Comment by Optiligence** [comment]
i can usually just select the previous driver letter and path again in the map network drive menu
without having to disconnect it first
a little less annoying

it can also simply show as disconnected (after e.g. displaying a message box that a resource is unavailable) and simply opening it while it has the disconnected symbol (sometimes it only appear after F5) reconnects it

**Comment by fabeit** [comment]
Is it possible to have an auto-reconnect like autofs?

**Comment by billziss-gh** [comment]
Latest beta version of WinFsp supports automatic restarts of file systems:

https://github.com/billziss-gh/winfsp/releases

Open the registry at `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\WinFsp\Services\sshfs` and add a new DWORD value with name `Recovery` and value `1`.

**Comment by Optiligence** [comment]
@billziss-gh thanks for the info; from changelog and commit it wasn’t obvious how/where exactly to apply it

Do you plan on making that a default?

**Comment by fabeit** [comment]
thank you for the information. I have tried it but it doesn't seem to work. In the registry I also have Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\WinFsp\Services\sshfs.k and sshfs.r, do I have to add the key to all three?

**Comment by fabeit** [comment]
![image](https://user-images.githubusercontent.com/10210185/81202565-16ae3180-8fc7-11ea-8920-228b56470a93.png)

**Comment by billziss-gh** [comment]
@Optiligence I may make this default for SSHFS-Win in the future.

@fabeit you have to add this registry setting to all keys that you want to use. Safest is to apply it for all keys: sshfs, sshfs.k and sshfs.r

**Comment by Tiwas** [comment]
Sorry for kicking a dead horse, but...should I upgrade sshfs, and if so - how do I check which version I'm running?

This would be a life saver for me, so I'm looking forward to not having to remotely log into my server to see if the reason it's not syncing is because of the file system not being available...or if there's something else wrong.

**Comment by demogorgonz** [comment]
This is still important, auto reconnect feature does not work with registry edit/s.

**Comment by guenhter** [comment]
Yeah, it sitll seems not to connect automatically.

**Comment by WildRiley** [comment]
As of August 26 2025, mounted drives do not reconnect, the drive unmounts when it can't reach the network. Forcing me to remount it again through cmd or file explorer.
