### ISSUE TITLE
Create new folder: Exception: STATUS_ACCESS_VIOLATION at rip=001800CC607

### ISSUE THREAD

**Issue by mablinov** [billziss-gh/sshfs-win#112]
Hi All, I've been experimenting with this software today, and decided to try to sshfs mount the home directory of a local RPi. It is running the latest revision of the software (apt update && apt upgrade).

versions of things:

sshfs-win: d08bc2bc9a4066e50fdd1443d9838251dd7d34c4 sshfs-win: do_cmd: check arg count
sshfs: 695cd8916f0e78d28009de3ffe112b9d1a1c9e5e Released 3.5.2

When I try to create a new folder, I receive the following error message dialog:

![sshfs-error-dialog](https://user-images.githubusercontent.com/10012248/66259846-74b73400-e7ae-11e9-9f0e-6afd96871195.PNG)

I would rather use keys rather than passwords, so I have done the mod described by https://github.com/billziss-gh/sshfs-win/issues/1#issuecomment-417147184 by applying the following modifications:

```
$ git diff sshfs-win.c
diff --git a/sshfs-win.c b/sshfs-win.c
index 1788887..d91e9ae 100644
--- a/sshfs-win.c
+++ b/sshfs-win.c
@@ -79,12 +79,11 @@ static int do_svc(int argc, char *argv[])
 {
 #define SSHFS_ARGS                      \
     "-f",                               \
-    "-opassword_stdin",                 \
-    "-opassword_stdout",                \
     "-orellinks",                       \
     "-ofstypename=SSHFS",               \
     "-oUserKnownHostsFile=/dev/null",   \
-    "-oStrictHostKeyChecking=no"
+    "-oStrictHostKeyChecking=no",      \
+    "-oIdentityFile=C:/Users/Maxim/Documents/rpi/rpi.pem" \

     if (3 > argc || 200 < argc)
         usage();
```

The `cmd.exe` instance from which I started `sshfs-win.exe` looks the following from start to finish:

(Aside: One strange feature is that it always warns me about how its "permanently" adding the fingerprint to the list of known hosts, every time I run exactly the same command.)

```
C:\Users\Maxim>sshfs-win.exe svc \sshfs\pi@192.168.0.5 S:
Warning: Permanently added '192.168.0.5' (ECDSA) to the list of known hosts.
Enter passphrase for key 'C:/Users/Maxim/Documents/rpi/rpi.pem':
The service sshfs has been started.
Exception: STATUS_ACCESS_VIOLATION at rip=001800CC607
rax=000006FE7FCF0010 rbx=00000006000E7180 rcx=000000003000B615
rdx=000000018030B0A8 rsi=00000006002B0000 rdi=000006FE7FFA0010
r8 =000006F87FCF0010 r9 =0000000180310000 r10=0000000003000000
r11=00000001004014C1 r12=00000000000000A0 r13=000000000074D910
r14=0000000002FFCA80 r15=0000000000000000
rbp=0000000000000000 rsp=0000000002FFC7C8
program=C:\Program Files\SSHFS-Win\bin\sshfs.exe, pid 1065, thread
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
00000000000  001800CC607 (00002FFC820, 00180151341, 003FEE3F746, 006002360B8)
00000000000  0010040610B (00600006C60, 006000E7180, 001800C88DE, 0000076B8A0)
00002FFC8F0  0010040A15E (0010040538C, 00000000005, 000000009B2, 00000000A02)
00002FFC9E1  7FF902292E2C (00002FFCA80, 00000000000, 00180152ECE, 00000000000)
00002FFC9E1  7FF902295E3F (00600092BB0, 00000000000, 00002FFCA74, 00002FFCA7C)
00002FFCAE1  7FF90229699C (00000763270, 00000000080, 00000000000, 00000000010)
0000074D910  7FF9022A310E (00000767240, 00000000090, 00000100001, 00000763270)
0000074D910  7FF9022A3FF5 (00000000000, 00000767240, 000000303E9, 00000763270)
0000074D910  7FF9022A6611 (00000000000, 000000000A0, 7FF9022A6410, 00000000000)
0000074D910  00180048353 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180048404 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  7FF91BCF4034 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  7FF91E683691 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace

C:\Users\Maxim>
```

If I navigate the directory structure of the sshfs'd directory with mingw git bash (I have mingw+cygwin) and try to `mkdir test`, then I also get "Input output error", and the `cmd.exe` service dumps again.

Any ideas?

**Comment by mablinov** [comment]
Update: I just discovered, that although upon folder creation the `sshfw-win.exe` process crashes, the folders do get created. I can confirm this by restarting `sshfs-win.exe` and viewing them in both explorer, and by actually sshing into the machine and listing the directory structure that way.

**Comment by billziss-gh** [comment]
This is a known problem. If you are using the latest SSHFS-Win BETA you must also use the latest WinFsp BETA that resolves this issue. See release notes here: https://github.com/billziss-gh/sshfs-win/releases

**Comment by mablinov** [comment]
Thanks for the pointer, everything now works fine.
