### ISSUE TITLE
can't disconnect via explorer nor net use

### ISSUE THREAD

**Issue by meeotch** [billziss-gh/sshfs-win#119]
I've got drive mapping working, both from explorer and via net use:

`net use X: \\sshfs.r\user@domain.net!port/mnt/X`

But I am not able to disconnect in explorer (just does nothing), nor via `net use X: /d` (returns "X: was deleted successfully", but the drive stays mapped.

Sometimes, switching my wifi connection to a different network solves the problem & the drive disappears.  But sometimes, it leaves the connection visible in explorer with a red "X" indicating it's not functioning.  In these latter cases, "net use" shows no mapped drives - but the drive can be re-mapped.

I discovered the hint about Network Provider order, and made sure Windows File System Proxy is the top provider in the list.  System is Win10 64-bit.

What else can I do to debug this issue?  Worst case:  is there a "nuclear option" for unmapping drives, without rebooting/logging out?  I'll be traveling quite a bit this winter, and having the username/domain/port of my server visible in the explorer sidebar (even if it's not connected) is a security problem, should my laptop ever get pinched.

**Comment by billziss-gh** [comment]
If WinFsp is the first one in the network provider order, this really should work. I have not heard any problems with this particular feature for quite some time now.

Can you please post the output of the `diag.bat` file that is found in the `\Program Files (x86)\WinFsp\bin` directory?

There is also the `launchctl` utility (in the same directory as above) which can be used to stop the file system. First run `launchctl-x64 list` to list all sshfs-win instances and then stop the ones you want with `launchctl-x64 stop`. This last one should work unless your installation is corrupted.

And finally the "nuclear" option is to kill the `sshfs.exe` process, which will forcibly unmount the file system. This is safe to do under WinFsp.

**Comment by meeotch** [comment]
Thanks for the quick (and thorough) response.  In the interim, I seem to have gotten it working via SiriKali.  I'm liking this route better - 1) it doesn't put the login/address info into the name displayed in explorer (so, just a drive letter), and 2) killing the sirikali interface seems to kill all mounts.

If you'd like, I can still post diagnostic info.  Or, since I'm the only one reporting the problem, you can spend your time on higher priorities.

At the risk of hijacking my own thread:  I tried searching for info about using private/public key auth with sshfs-win, but the results seemed to be a bunch of arcane script-fu and auth server stuff.  Is this still the current status?  

(I tried passing an IdentityFile argument via sirikali's options, but it my /var/auth.log on the server side indicates that it's still trying passwords.  I'll post this question to sirikali as well, if there's no updated info here.)

**Comment by billziss-gh** [comment]
> At the risk of hijacking my own thread: I tried searching for info about using private/public key auth with sshfs-win, but the results seemed to be a bunch of arcane script-fu and auth server stuff. Is this still the current status?

Unfortunately yes. I simply do not have the time to make sure that sshfs-win supports all scenarios that people want to use it in.

**Comment by mhogomchungu** [comment]
Developer of SiriKali here.

SiriKali does support connecting sshfs-win to ssh servers using:
1. Password authentication.
2. Key Agents and i use KeePass 2 for testing.
3. Public key authentication.

**Comment by billziss-gh** [comment]
@mhogomchungu thanks for clarifying the authentication functionality supported by SiriKali. I added a note to the project's README detailing this information.

https://github.com/billziss-gh/sshfs-win/blob/master/README.md#gui-front-end

**Comment by brianlturney** [comment]
I currently have the same issue with sshfs. Im not able to disconnect the drive not matter what I try.

**Comment by Kyogre** [comment]
I suggest you to tru execute such two commands:
```
net use Z: /del
net use \\sshfs\\<your connection string> /del
```
By `your connection string` I mean exact string which you specified when added the drive, like `\\sshfs\root@192.168.111.100!23/mnt/X`

Finally, you can restart `Win.Fsp.Launcher` service to unmount all its drives.
