### ISSUE TITLE
Data integrity violated when copying and replacing file (null bytes error)

### ISSUE THREAD

**Issue by ale152** [billziss-gh/sshfs-win#123]
Hello,

I'm experiencing an issue when copying and replacing a file on a remote server.
If I copy a file to a remote location where the same file already exists, replacing that file produces a new one with many null bytes hidden in it. The final file size is almost doubled and the copied one is hence compromised.
This problem doesn't arise if I delete the file first and then copy it, it only happens when I replace the file.

I'm using SSHFS-Win 3.5 BETA and WinFsp 2019.3 B3 on Windows 10 1903

Thank you

**Comment by b52** [comment]
I'm having similar issues. This does not only involve replacing files, but also simply copying files where null bytes get prepended.

**Comment by billziss-gh** [comment]
Please download and install latest WinFsp 2020, which resolves this problem.

**Comment by billziss-gh** [comment]
Closing this as I believe it is resolved with WinFsp 2020 or later. Please reopen if you find otherwise.
