### ISSUE TITLE
x86 binary missing

### ISSUE THREAD

**Issue by myroad94** [billziss-gh/sshfs-win#13]
Hi,

I installed latest winfsp-1.1.17192 and sshfs-win-2.7.17038. Contrary to winfsp, sshfs-win installed a x64 binary in my x86 system. I searched the x86 binary everywhere, where is-it?

**Comment by billziss-gh** [comment]
There currently is not any x86 binary of SSHFS-Win.

If you have a working 32-bit installation of Cygwin, it is not hard to create one. You must install the latest version of WinFsp and also install the included cygfuse (it can be found under `\Program Files\WinFsp\opt`). Then (assuming that you have the necessary dev tools installed under Cygwin) you should be able to run `make` and get a 32-bit version of SSHFS-Win.

**Comment by myroad94** [comment]
Ok, thank you. You should write a warning in sshfs page, because I and other people spent some time figuring what was wrong.

> Then (assuming that you have the necessary dev tools installed under Cygwin) you should be able to run make and get a 32-bit version of SSHFS-Win.

Do you know what is the minimum packages list that Cygwin need? (I guess make), then
```
git clone https://github.com/billziss-gh/sshfs-win.git
git checkout 2.7
cd sshfs-win
./configure
./make

```
I will try that. But the missing x86 binaries are really a barrier to a popular adoption by end users, it would be great to add it one day :)

**Comment by billziss-gh** [comment]
> I will try that. But the missing x86 binaries are really a barrier to a popular adoption by end users, it would be great to add it one day :)

Point taken. I will look into adding it in the future :)

> Do you know what is the minimum packages list that Cygwin need?

I think they are the usual suspects: gcc, autoconf, etc. and also the packages required to compile SSHFS:

https://github.com/libfuse/sshfs/blob/a9a1cc004675f35df34c68f3e134c2194311943f/configure.ac#L47

FUSE is provided by WinFsp (look in `\Program Files\WinFsp\opt`), but Glib should be installed using the Cygwin installer.

----

If you succeed in building this it would be very helpful if you provided the instructions here or as a PR in the README ("How to build").

**Comment by fbreitwieser** [comment]
I ran into the same issue on my 32-bit Windows 7 VM. It installed fine, and when trying to map a network drive it even asked for the password, but then it just does not work. I also took me some time to figure out what was going on. It would be very appreciated if you warn users during or after installation that it does not work on 32bit machines.

**Comment by billziss-gh** [comment]
Commit d1b9487b5d5b89c607c3306e26d61e52315aeeac will fix this.

Unfortunately some other changes require the final release of WinFsp v1.2, so I cannot release binaries yet.

**Comment by billziss-gh** [comment]
The latest SSHFS-Win release now inludes x64 and x86 binaries.

https://github.com/billziss-gh/sshfs-win/releases/latest

**Comment by myroad94** [comment]
I confirm it works in 32bit, excellent release!

**Comment by billziss-gh** [comment]
Great to hear!
