### ISSUE TITLE
Can not properly rename drives in Explorer?

### ISSUE THREAD

**Issue by IngwiePhoenix** [billziss-gh/sshfs-win#131]
Hey! Really appreciate having SSHFS on Windows - thank you very much for the work!

However, when the drive is initially created, it has a really long name, and I would like to change that. Unfortunately, I seem to be capped in the amount of characters I can put into the name, whilst the original name is way above that. Any reason for that?

Thanks in advance!

**Comment by billziss-gh** [comment]
I just tried this on my Win10 installation and was able to rename an sshfs drive to "mydrive". Just right click on the drive and choose "Rename".

**Comment by IngwiePhoenix** [comment]
You misunderstand ^^;

When adding a drive, then this is the name it gets assigned by windows: `home (\\sshfs.r\root@ingwie.io)`
But I can only rename it to a certain length - this being the maximum: `home at ing` (wanting to add "ingwie.io" there.)

It seems that there is a limitation in characters in terms of names being assignable.

**Comment by billziss-gh** [comment]
If there is indeed such a limitation (I cannot check this right now), it has nothing to do with SSHFS. This is completely handled by Windows Explorer, that stores the name in the registry.
