### ISSUE TITLE
Release sshfs-win with support for sshfs.k prefix

### ISSUE THREAD

**Issue by brighamandrew** [billziss-gh/sshfs-win#139]
I originally downloaded and installed first sshfs-win versions 2.7.17334 then 3.5.19106.

I have downloaded and installed first winfsp versions 1.4.19049 then 1.519352.

I am attempting to map a network drive with Windows Explorer using UNC syntax with sshfs.k prefix and key-pair authentication.

I have an openssh compatible private key at %USERPROFILE%/.ssh/id_rsa and can successfully ssh into the server on the command line using key pair authentication.

Using both the above versions, whenever I try to use the sshfs.k prefix, windows gives me a network error:

![image](https://user-images.githubusercontent.com/19918108/71490588-b0c7c700-27e8-11ea-9f24-a774341c78fb.png)

I can connect and successfully map a drive with sshfs-win using the normal sshfs and sshfs.r prefixes and password authentication.

So now I'm at a loss as to why sshfs-win isn't allowing the sshfs.k prefix to work since it works using the sshfs and sshfs.r prefix and password authenticaion and I can ssh in using the key on the command line. I would appreciate any advice, thank you.

**Comment by tatsy** [comment]
I encountered the same problem. My version is v2.7.17334, which is currently the latest version. Does anyone know about this problem?

**Comment by billziss-gh** [comment]
Sorry, there is no official release which supports the sshfs.k prefix yet.

**Comment by nagstaku** [comment]
Darn, I just ran into this issue as well, and reading the main documentation it sounds like this feature should be working.

Is there a work around to manually launch sshfs from the command line and get it to use keys?

**Comment by billziss-gh** [comment]
The latest release support the `sshfs.k` prefix. Get it from here:

[SSHFS-Win 2020](https://github.com/billziss-gh/sshfs-win/releases/tag/v3.5.20024)
