### ISSUE TITLE
Does sshfs-win support socks5 proxy?

### ISSUE THREAD

**Issue by bobjiang82** [billziss-gh/sshfs-win#152]
I have a Linux machine in a subnet which can only be accessed through socks5 proxy from my laptop.
e.g.
A: My laptop (windows) ----> B: socks5 proxy server ----> C: the target machine
The related settings in C:\Users\myname\.ssh\config is as below,
host C_IP
    User root
    ProxyCommand ncat --proxy-type socks5 --proxy B_IP:1080 %h %p

Is it possible to sshfs mount C on A? I tried and it never succeeded. So I wonder if sshfs-win support this usage.
Thanks.

**Comment by billziss-gh** [comment]
Sshfs-win does not support any specialized scenarios out of the box. You can try using the included `sshfs-win.exe` or `sshfs.exe` executables from the command line and attempt to do what you want to do. Scenarios that work on Linux may or may not work on Cygwin.

**Comment by bobjiang82** [comment]
I followed the method in the link below and the sshfs with socks5 proxy worked well! Thanks.
https://github.com/billziss-gh/sshfs-win/issues/98

**Comment by ds6** [comment]
This won't work because ProxyCommand tries to call `/bin/sh` which does not exist.
For example, with this config file as `ProxyCommand.config`:
```LogLevel DEBUG

Host hostB
	HostName 12.34.56.78
	User ds6
	ForwardAgent yes

Host hostC
	HostName 87.65.43.21
	User ds6
	ProxyCommand /bin/ssh B -W %h:%p```

```C:\Program Files\SSHFS-Win\bin>sshfs-win cmd hostC:/ X: -F ProxyCommand.config -f
debug1: Executing proxy command: exec /bin/ssh 12.34.56.78 -W 87.65.43.21:22
/bin/sh: No such file or directory
...
kex_exchange_identification: write: Broken pipe
read: Connection reset by peer```
