### ISSUE TITLE
Custom ports not working

### ISSUE THREAD

**Issue by darkcharmander** [billziss-gh/sshfs-win#160]
I have an SFTP server running at a custom port. I've tried many variants of commands and SiriKali is also not handling it properly. The username, ip and port are scrambled for obvious reasons, these are some commands that I've tried:

sshfs-win svc \username@1.2.3.4:65535 Z:
sshfs-win svc \username@1.2.3.4!65535 Z:
sshfs-win svc \username@1.2.3.4[!65535] Z:
sshfs-win svc \username@1.2.3.4@65535\ Z:
sshfs-win svc \username@1.2.3.4!65535\ Z:
sshfs-win svc \username@1.2.3.465535\ Z:
sshfs-win svc \username@1.2.3.4 Z: -p 65535
sshfs-win svc \username@1.2.3.4 Z: --port 65535
sshfs-win svc \username@1.2.3.4 Z: username -p 65535
sshfs-win svc \username@1.2.3.4 Z: username --port=65535

One of these might be invalid, I do not remember which one but they give the same result: Connection refused, port 22.
Or Windows will instantly ask you again for your credentials when trying it from Windows explorer with a custom port.

I've also read issue #122 but that doesn't solve it unfortunately. When I type in explorer: \\sshfs\root@xx.xx.xx.xx!4222 (But then my username, ip and port), windows asks for my credentials. After entering them, nothing happens and windows will show a popup after a while, telling you there's maybe something wrong with my network (Which is obviously not the case).

I know for a fact that this server with SFTP on a custom port is working flawlessly since I can connect with it using another SFTP tool on the same PC. Also from other devices it works fine.

Am I doing something wrong here or is sshfs-win not properly supporting custom ports?

**Comment by billziss-gh** [comment]
The correct syntax is:

    sshfs-win svc \sshfs\username@1.2.3.4!65535 Z:

**Comment by darkcharmander** [comment]
When I execute that command in a terminal, it just hangs infinitely. Whenever I press enter, it says 'Connection reset by peer'. Nothing happens unfortunately.

**Comment by garoto** [comment]
It's waiting for a password.

**Comment by darkcharmander** [comment]
Thanks for your help guys. This is what happens  after I enter a password:

```
sshfs-win svc \sshfs\username@1.2.3.4!65535 Z:
[MyPassword]
OK
The service sshfs has been started.
```
From that moment on there is no more output, the process seems to remain idle. I do not see a drive appear and I cannot access supposed drive by any means. Executing the 'net use...' variant of the mount comment also doesn't work (That one doesn't even want to connect).

What is perhaps interesting is the output from the 'net use':
```
Status       Local     Remote                    Network

-------------------------------------------------------------------------------
             Z:        \\sshfs\username@1.2.3.4!65535
                                                WinFsp.Np
```
This means it must be connected, but not working well? Another SMB mounted drive reads 'OK' in the status column so that means there must be something wrong here.

**Comment by darkcharmander** [comment]
Just posting some additional info which might be of use:
Server OS: Debian Bullseye, x64
Openssh-server: 1:8.2p1-4,
Client OS: Windows 10

SSH Jails (ChrootDirectory) are active on the server. I temporarily disabled them but it still gives the same result.

**Comment by garoto** [comment]
Not sure, give this a try perhaps:
```
sshfs-win svc \sshfs\username@1.2.3.4!65535 Z: "%userdomain%\%username%"
```

**Comment by darkcharmander** [comment]
Executing that gives the same output and behavior as the previous command. No drive to be seen anywhere.

**Comment by billziss-gh** [comment]
@darkcharmander the `net use` command output indicates that the file system is working and should be accessible as the Z: drive.

If you cannot see the Z: drive from (e.g.) Explorer, then the reason is that you started the file system from an Administrator command prompt. Kill the file system and restart it from a regular command prompt. (Windows uses a different drive namespace when starting a file system from a regular prompt versus an elevated prompt.)

**Comment by darkcharmander** [comment]
I used a regular prompt instead of an elevated one, and it worked! The drive appears like it's supposed to.

Thank you so much @billziss-gh!

**Comment by billziss-gh** [comment]
@darkcharmander glad to hear that this was resolved.

**Comment by Rayanfer32** [comment]
Its wierd that you need to use ` !` instead of ` : ` fort custom port to work
