### ISSUE TITLE
x64 installer isn't allowed to run by SmartScreen

### ISSUE THREAD

**Issue by yonoqueriaestaraqui** [billziss-gh/sshfs-win#165]
When run, the installer makes WDSS [1] to show this warn:

![image](https://user-images.githubusercontent.com/62750118/77755071-cee1d500-702c-11ea-8962-e3b8ecfeb334.png)

Seems nothing else can be done.

[1] https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-overview

**Comment by billziss-gh** [comment]
Interesting. On my systems when this appears I also get a link for "More information" and when I click on it I get an extra button which allows me to run it.

![Screen Shot 2020-03-27 at 11 49 38 AM](https://user-images.githubusercontent.com/15330948/77790024-50336a80-7021-11ea-927e-dc24d9252522.png)

Which version of Win10 are you using? Or perhaps you have a very strict Windows Defender setting?

**Comment by yonoqueriaestaraqui** [comment]
Indeed, this is a corporate device, and the Windows Defender "Check apps and files" setting is set to "Block". Unfortunately it's a "This setting is managed by your administrator", so I can't do much about that. I just wonder how other installers are able to bypass that and be happily accepted but sshfs-win can't. Thanks for your help anyway!

**Comment by billziss-gh** [comment]
Try the beta installer which is now signed, so this should no longer be a problem.
