### ISSUE TITLE
System error 67 or "cannot access" when trying to mount \\sshfs\something

### ISSUE THREAD

**Issue by omnichronous** [billziss-gh/sshfs-win#17]
I've been using Ubuntu so far, where I used `sshfs` to mount a remote filesystem. Now, under **Windows 7 Pro** I've installed SSHFS-Win, and then WinFsp, and I'm trying to mount that same filesystem, but it fails. Using the Map Network Drive interface I try pointing to `\\sshfs\myusername@website.i.want`. It asks for my user and password and immediately after I enter them I get the "cannot access" error.

![untitled](https://user-images.githubusercontent.com/8319869/33724918-6bf9d586-db79-11e7-8a9e-bca2f9da1717.png)

Trying the `net use` way goes like this:

```
net use \\sshfs\myusername@website.i.want:/var/www/mydir
The password is invalid for \\sshfs\myusername@website.i.want:/var/www/mydir.

Enter the user name for 'sshfs': myusername
Enter the password for sshfs:
System error 67 has occurred.

The network name cannot be found.
```

Now I've tried every possible syntax variation I could think of, but to no avail. I've checked the comment in this issue https://github.com/billziss-gh/winfsp/issues/21#issuecomment-246027327 and mounting `\\memfs64\share` works for me. On the other hand, I've also tried simply running `sshfs myusername@website.i.want:/var/www/mydir C:\mydir` in the console and after a password prompt the folder gets mounted with no problems.

Could this possibly be an issue with special characters in my password or something? If so, why does one way work and others - not?

I would really appreciate some help with figuring this out.

**Comment by billziss-gh** [comment]
I believe the share that you use should be `\\sshfs\myusername@website.i.want\var\www\mydir`. Notice the lack of a colon and the use of backslashes.

Presumably you want to access your system's `/var` directory. People have reported success in accessing root directories by using a double backslash: `\\sshfs\myusername@website.i.want\\var\www\mydir`

**Comment by omnichronous** [comment]
Unfortunately both of these also lead to the same errors.

**Comment by billziss-gh** [comment]
I can confirm that the problem described in the OP is a problem on Win7. Unfortunately I do not have a solution.

The problem appears to be that the launcher service (WinFsp.Launcher) is unable to launch the SSHFS-Win file system. This is because the `CreateProcessW` Windows API fails with `ERROR_NO_SYSTEM_RESOURCES` when launched with `EXTENDED_STARTUPINFO_PRESENT`. This special invocation of `CreateProcess` is used when launching a file system that requires credentials. Normal invocations of `CreateProcess` work.

This failure is specific to Windows 7 and does not happen on Win8+. This leads me to believe that it may be a Win7 bug and that we will need a workaround for this OS.

**Comment by omnichronous** [comment]
I appreciate you looking into this. Lucky for me my sysadmin set me up with Samba shares in the meantime.

**Comment by Shaddoh** [comment]
I am having the same issues on win 7 machines. Just chiming in so I am on the thread and get notified if you find a work around.

I have found this works but does not persist on boot

Open a command prompt.
cd C:\Program Files (x86)\SSHFS-Win\bin
set CYGFUSE=WinFsp
set PATH=C:\Program Files (x86)\SSHFS-Win\bin
sshfs.exe -f -o idmap=user user@server: z:
Gives a RSA authentification error, buit lets you say yes or no to connect. 
After this it says service has started and you type in password.

**Comment by billziss-gh** [comment]
Commit billziss-gh/winfsp@b2e474658db4bc3fd3ac92342b4aa8e867090f29 should fix this.

This commit works around the `CreateProcessW` problem on Win7. Since this is an important problem that makes SSHFS-Win unusable for most on Win7, I am planning to release an update to WinFsp 2017.2 that will include this fix soon.

**Comment by billziss-gh** [comment]
The latest [WinFsp release](https://github.com/billziss-gh/winfsp/releases/tag/v1.2POST1) is out and should fix this problem. Please try it and let me know.

**Comment by Sgmaster** [comment]
Hello, sorry for opening this after almost 2 years, but I experience the exact same issue as OP, exact same errors and all as OP on Windows 10 Pro x64 using last stable version of sshfs.

In ubuntu I use to connect to the remote filesystem with the following command:
`sshfs -p 8080 myusername@website.i.want: local_dir`

But using sshfs-win, with the following command on either net use and/or on Windows Explorer and Networks, I keep getting the same errors as OP.
`net use X: \\sshfs\myusername@website.i.want[!8080]`

Any thoughts on why it might be happening and/or any potential fix would be really appreciated :)

**Comment by abaheti95** [comment]
I am on a windows 10 device using latest version and I can ping the server but sshfs is not working. On the other hand I am able to connect using SFTP which is weird.

**Comment by SzieberthAdam** [comment]
Same here on Win 10, WinFsp 1.4.19049, SSHFS-Win 2.7.17334.

**Comment by Feriman22** [comment]
I had same issue, it solved after reboot my PC.

**Comment by wuyihung** [comment]
Same on Win 10 1909, WinFsp 2020.2 (1.8.20304), and SSHFS-Win 2021 (x64) (3.5.20357)

**Comment by aparico** [comment]
I had a similar problem too (Windows 10, winfsp-1.10.22006, sshfs-win-3.7.21011-x64). 
I used this repo and [another one](https://github.com/evsar3/sshfs-win-manager) and it worked!
