### ISSUE TITLE
Mounting in folder, not as disk (mklink)

### ISSUE THREAD

**Issue by paulzi** [billziss-gh/sshfs-win#172]
`net use p: \\sshfs.k\root@192.168.1.2` - is worked
`mklink /d "c:\server" "\\sshfs.k\root@192.168.1.2"` - works, but not accessible
It's possible to mount in folder?

Maybe problem in not worked direct input in explorer?
`\\sshfs.k\root@192.168.1.2` - direct input in explorer now work

**Comment by billziss-gh** [comment]
It is possible to mount SSHFS on a directory rather than a drive, but you have to use the command line to do it. You cannot use the `net use` mechanics.

**Comment by paulzi** [comment]
I use
`mklink /d "c:\server" "\\sshfs.k\root@192.168.1.2"`
for mount in folder. Symlink is created but not accessible.

**Comment by msomali** [comment]
@paulzi @billziss-gh 
I do not use command line but this method worked for me in mounting a directory using Map Network Drive in Windows:
`\\sshfs.r\user@host\..\..\my_directory`

**Comment by paulzi** [comment]
Worked on sshfs-win-3.7.21011-x64/winfsp-1.9.21096
