### ISSUE TITLE
How connect to a secondary Windows drive ?

### ISSUE THREAD

**Issue by WhoapBuddy** [billziss-gh/sshfs-win#177]
Hi,

how can I have windows connect using sshfs to another Windows host secondary disk (ie. D:) ?

Thanks,

**Comment by Coradol** [comment]
bump! need that too.

**Comment by billziss-gh** [comment]
Unless I misunderstand your question this is not an issue that has to do with SSHFS-Win directly. You will likely have to run an SSH server on the second Windows host and configure it correctly.

**Comment by WhoapBuddy** [comment]
> Unless I misunderstand your question this is not an issue that has to do with SSHFS-Win directly. You will likely have to run an SSH server on the second Windows host and configure it correctly.

Thats not a SSH server issue - I told you I can reach a secondary disk via SSH.
What I can't do is reaching the secondary disk using SSHFS-Win - the temporary solution I am using now is the following in my Windows cmd prompt:

cd C:
mklink DISK-D D:\ /J
\\sshfs.r\user@host\DISK-D\
 
I am wondering if there is a way to reach disk D: without using this trick.

Thanks,

**Comment by zzilch** [comment]
Wondering the same problem.
