### ISSUE TITLE
Installation Instuctions?

### ISSUE THREAD

**Issue by infinityends** [billziss-gh/sshfs-win#18]
Readme file doesn't explain how to actually install SSHFS. It simply starts with once WinFSP and SSHFS are installed use these commands. Maybe I am missing some other instructions somewhere, but I haven't found an installer, or instructions on what to do with the files to compile them, or if they just need to be dropped in place somewhere in the WinFSP folder.

**Comment by billziss-gh** [comment]
Fair enough. I will update the README with more detailed instructions.

What you need to do:

- Install latest release of [WinFsp](https://github.com/billziss-gh/winfsp/releases/latest).

- Install latest release of [SSHFS-Win](https://github.com/billziss-gh/sshfs-win/releases/latest). Choose x64 or x86 according to your computer's architecture.

**Comment by billziss-gh** [comment]
Commit 4bbe9b29fce636e4b4d2a88712ca396301876146 adds README instructions.
