### ISSUE TITLE
Problems using sshfs and cannot get a password prompt using sshfs-win

### ISSUE THREAD

**Issue by andyneff** [billziss-gh/sshfs-win#182]
Ever since I started trying to use this last week, I am not able to use sshfs for windows in the preferred methods mentioned in the Readme.

The most perplexing detail is that `sshfs-win` never prompts me for a password. The only time I can get a password prompt is when I use `sshfs` directly.

A lot of things appear to be going wrong. What am I doing wrong?

## Version info

SSHFS version 3.5.2
FUSE library version 3.2
WINFSP 1.6
Windows 10 Pro: 10.0.19041

## What I've tried

1. Attempting to mount using the windows Map Network Drive UI, does not work
    - This method does ask me for a user name and password, however It doesn't work. It just hangs for a while before erroring out. I can see that both `sshfs-win.exe` is started (with the expected arguments), and `sshfs.exe` is started (no arguments?), and SSHFS's `ssh.exe` starts (with no argument)
    - Eventually I get ![image](https://user-images.githubusercontent.com/7596961/80021697-e9329580-84a8-11ea-9dfd-3ebd48db1a93.png)
2. Start, Run, `\\sshfs\{username}@{computername}\somedir_in_my_home` does not work either. That just hangs and nothing starts.
    - No `sshfs-win.exe` or `sshfs.exe` processes start
    - Eventually I got the similar error: 
![image](https://user-images.githubusercontent.com/7596961/80029285-9363ea80-84b4-11ea-84b9-5c1b48b7f7a0.png)

3. I have tried `sshfs-win svc \sshfs\{username}@{computername}\somedir_in_my_home y:` And that too fails.
    - Once I press enter (once) to execute the command, nothing really happens, but `sshfs-win` (with the exeptect arguments) is running, and `sshfs` with no arguments is running too
    - I can press enter a _second_ time, and then SSHFS's `ssh.exe` starts, with no arguments
    - I also tried `\\sshfs\` instead of `\sshfs\` (which is what the readme says), no difference.
4. I have tried `sshfs-win svc \sshfs\{username}@{computername}\somedir_in_my_home y: {windows_domain}/{windows_username} -o "`
5. Calling `sshfs.exe` directly gives a password prompt, but in either "password authentication" or "keyboard-interactive authentication", it fails with `read: Connection reset by peer`
- Other than the "Map Network Drive", I **never** get a password prompt???

## Workarounds

1. My best success was calling `sshfs-win cmd`
    - `sshfs-win cmd {username}@{computername}:/home/{username}/bin x:`
       - This actually does ask for my password, and unlike calling `sshfs.exe`, I don't get the `read: Connection reset by peer` error
    - sshfs runs in the background so I'm free to close the command prompt when I'm done
    - However the drive does _not_ show up as a network drive, but as a local drive.
    - It's not like `net use X: /delete` worked in the first place, so I didn't lose much
    - The only way to disconnect the drive is to find one of the two `sshfs.exe` pids and kill it.
    - The `sshfs` command works when using either "password authentication" or "keyboard-interactive authentication", using SSHFS's `ssh.exe`.
    - Only when I call `sshfs.exe` directly (instead of `sshfs-win.exe cmd`), do I see arguments in `Task Manager` on `sshfs.exe`
2. While `sshfs-win svc \sshfs\{username}@{computer}\some_dir x: {windows_domain}\{windows username} -o ssh_command="c:\\\\windows\\\\system32\\\\wsl ssh"` did work, it was not obvious that I needed _four_ slashes, why I needed extra slashed, nor why I had to specify the full path for `wsl` in this case, when it's obviously on the path (althought it's probably not on "Local Service"'s path), but it did "work"
    - I still had to type that mysterious second enter to get it to connect
    - `net use` does show the X: drive
        ```
        C:\Users\***\Desktop>net use
        New connections will be remembered.
        
        
        Status       Local     Remote                    Network
        
        -------------------------------------------------------------------------------
        OK           F:        \\***\***   Microsoft Windows Network
        Unavailable  V:        \\***\***
                                                        Microsoft Windows Network
                     X:        \\sshfs\***@***\bin    WinFsp.Np
        The command completed successfully.
        ```
        - Note: The F: drive says OK (Because I've accessed it since booting), the V drive says unavailable (because I haven't used it since booting), and X: (the only sshfs drive) says neither ok nor unavailable.
        - `net use X: /delete` fails 
            ```
            The network connection could not be found.
            
            More help is available by typing NET HELPMSG 2250.
            ```
    - Right clicking the drive and choosing disconnect results in
        ![image](https://user-images.githubusercontent.com/7596961/80025887-46c9e080-84af-11ea-94f8-71d48d83d900.png)
    - Also, `sshfs-win.exe` had to remain the the foreground, which is less than ideal, leaving a command prompt open for this....
    - Ctrl+C broke the sshfs drive, but did not make it go away
        - After Ctrl+C, X: no longer showed up in the `net use` list, and I couldn't get it to disappear no matter what I tried. Sometimes Ctrl+C will remove the drive, sometimes it will not. It appears to be random.
3. `sshfs andy@viola:/tmp X: -o ssh_command="wsl ssh"` also work
    - `sshfs-win cmd andy@viola:/tmp X: -o ssh_command="wsl ssh"` error with "read: Connection reset by peer", both using Shared connections and by authenticating

## Additional info

- All commands executed from `cmd.exe`
- SSHFS's `ssh.exe` does work just fine when I run `ssh {username}@{computer_name}`
- My `.ssh/config file reads:
    ```
    Host *
      PreferredAuthentications password,keyboard-interactive
    ```
- So that I get a single password prompt, which is the normal way to log into ssh for most applications, not keyboard-interactive. But both fail the same way.
- My particular remote computer uses a "one time use password" to log in (so you can never "remember password"), and I find it useful to use "connection sharing". Unfortunately, all (as far as I know) pure windows implementations of ssh do not support using/emulating unix socket files (since cygwin/mingw/window's ssh implementations refuse to emulate it...). However WSL 1 does not have this problem. This is why I use the WSL's ssh, which has the following `~/.ssh/config` files:
    ```
    Host *
      PreferredAuthentications password,keyboard-interactive
      IdentitiesOnly yes
      ServerAliveInterval 30
      ServerAliveCountMax 1
      ControlPersist 500
      ControlPath=~/.ssh/%C
      ControlMaster=auto
    ```
    - All I need to do is ssh in on WSL first, and I'm able to have password-less and secure ssh login (with out using an unencrypted Private key or ssh agent)

**Comment by andyneff** [comment]
- I just found out this "Mysterious enter" that I have to press after `sshfs-win svc` is because of [these](https://github.com/billziss-gh/sshfs-win/blob/master/sshfs-win.c#L215-L216) lines.
    - Why is the default behavior to go against the norm and echo the password on the screen?
    - Why is there no prompt, so that a someone would know that is a password prompt?

**Comment by andyneff** [comment]
Now that I've read the source, I realize this issue was too convoluted, will attempt to break it up into more reasonable pieces

**Comment by billziss-gh** [comment]
> I just found out this "Mysterious enter" that I have to press after sshfs-win svc is because of these lines.
>
> Why is the default behavior to go against the norm and echo the password on the screen?
> Why is there no prompt, so that a someone would know that is a password prompt?

The command line `sshfs-win svc` is not really meant to be used by users directly. Instead it is supposed to be used by the WinFsp Launcher. The WinFsp Launcher is a Windows service that is shipped with WinFsp which launches file systems when you "map network drive" or `net use`.

The Launcher has a protocol for passing passwords in stdin and expects the file system to respond "OK" on authentication success. That is why you do not see any password prompts, etc.; this particular protocol is meant to be used by software and not humans.
