### ISSUE TITLE
Problems disconnecting drive

### ISSUE THREAD

**Issue by andyneff** [billziss-gh/sshfs-win#183]
I have tried both the `net use X: /delete` and Right clicking and choosing connect. both methods fail

## Version info

SSHFS version 3.5.2
FUSE library version 3.2
WINFSP 1.6
Windows 10 Pro: 10.0.19041
Language: US English. So I shouldn't be having any korean issues like #178 

# Mounting

I have tried a few ways of mounting, but I can only mount from command line):

1. `sshfs-win cmd username@computername:/dirname X: -orellinks --VolumePrefix=\sshfs.r\computername`
2. `sshfs-win svc \sshfs.r\username@computername\dirname X:`

# Observed behavior

1. `net use` does show the X: drive
    ```
    C:\Users\***\Desktop>net use
    New connections will be remembered.
    
    
    Status       Local     Remote                    Network
    
    -------------------------------------------------------------------------------
    OK           F:        \\***\***   Microsoft Windows Network
    Unavailable  V:        \\***\***
                                                    Microsoft Windows Network
                 X:        \\sshfs.r\***@***\tmp    WinFsp.Np
    The command completed successfully.
    ```
    - Note: The F: drive says OK (Because I've accessed it since booting), the V drive says unavailable (because I haven't used it since booting), and X: (the only sshfs drive) says neither ok nor unavailable.
    - `net use X: /delete` fails 
        ```
        The network connection could not be found.
        
        More help is available by typing NET HELPMSG 2250.
        ```
2. Right clicking the drive and choosing disconnect results in ![image](https://user-images.githubusercontent.com/7596961/80025887-46c9e080-84af-11ea-94f8-71d48d83d900.png)

**Comment by billziss-gh** [comment]
How do you start the file system? If you start it by hand and not through the Launcher you cannot disconnect it using `net use X: /delete`

**Comment by andyneff** [comment]
I did try starting it using:

```
sshfs-win svc \sshfs.r\username@computername\dirname X:
```

Which as I understand is "WinFsp Launcher (sshfs-win svc)."? Or does launcher mean "Map Network Drive" graphically only?

**Comment by billziss-gh** [comment]
Actually it is the other way around. The Launcher is expected to start the file system using `sshfs-win svc`. Running `sshfs-win svc` does not go through the Launcher.

Look at the registry under `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\WinFsp\Services\sshfs` and you will see the command line that the Launcher sends to `sshfs-win`.

If you are interested in more details on how this works, please read the [Service Architecture](http://www.secfs.net/winfsp/doc/WinFsp-Service-Architecture/) document.

**Comment by andyneff** [comment]
Yes, I had already made sure the reg keys were set correctly.

Thanks for the explanation! I need to figure out #185 before I can `net use /delete` to work.

**Comment by andyneff** [comment]
> If you start it by hand and not through the Launcher you cannot disconnect it using `net use X: /delete`

Verified, Got the launcher working, and this fixed my problem! 👍

**Comment by billziss-gh** [comment]
Great!
