### ISSUE TITLE
Authentication with keys

### ISSUE THREAD

**Issue by continue98** [billziss-gh/sshfs-win#189]
Hi. How to use sshfs-win with ssh keys?

**Comment by billziss-gh** [comment]
See the notes [here](https://github.com/billziss-gh/sshfs-win#unc-syntax).

Use the `\\sshfs.k\[LOCUSER=]REMUSER@HOST[!PORT][\PATH]` and place your keys in `%USERPROFILE%/.ssh/id_rsa`.

**Comment by continue98** [comment]
Show a specific example (I don't understand how to set parameters correctly). For example, I need to connect to a remote folder: /etc with IP server 127.0.0.1

**Comment by continue98** [comment]
@billziss-gh Can you give us an example?
