### ISSUE TITLE
chocolatey version outdated

### ISSUE THREAD

**Issue by hongooi73** [billziss-gh/sshfs-win#195]
Hi, thanks for this package. I just installed it with choco, and tried to connect via a public key with the `\\sshfs.k\user@host` syntax. This failed with an error, and on checking, I found that the version that choco installed was still at [2.7.17334.](https://chocolatey.org/packages/sshfs) Are there any plans to keep the choco install route?

**Comment by Hong-Revo** [comment]
PS. somewhat related issue, the x64 msi from the releases page on this repo is unsigned, which triggered a warning from Windows Defender. I assume this is just an oversight.

**Comment by billziss-gh** [comment]
> I found that the version that choco installed was still at 2.7.17334

@4O4 maintains this chocolatey package. @4O4 any chance of seeing an updated version?

> the x64 msi from the releases page on this repo is unsigned, which triggered a warning from Windows Defender. I assume this is just an oversight.

Not really. While I have an EV certificate that I use to sign WinFsp, I have avoided the hassle for SSHFS-Win so far, thinking that people would just know to click "Run anyway".  But I have heard from some that this option is not always enabled, so perhaps it is worth signing the installer despite the hassle.

**Comment by 4O4** [comment]
I was trying to update the chocolatey package for about six months now but
I was unable to do so because of an error on their side. It is always
rejecting an updated package with some kind of unhandled exception, it's a
known and reported bug and last time I tried it still wasn't fixed.

**Comment by billziss-gh** [comment]
@4O4 thanks for the update and your efforts to update the package. I was not aware of the chocolatey issues.

**Comment by 4O4** [comment]
I'm still having the same issue over and over again.

![image](https://user-images.githubusercontent.com/4274691/83514617-41ab7880-a4d4-11ea-876b-9abd5e33216a.png)

I'm starting to think it would be better if I've just removed the package and @billziss-gh you could try to add it yourself.

**Comment by 4O4** [comment]
https://github.com/chocolatey/chocolatey.org/issues/798

**Comment by Hong-Revo** [comment]
Maybe worthwhile distributing via winget instead of/in addition to choco?

https://devblogs.microsoft.com/commandline/windows-package-manager-preview/
https://github.com/microsoft/winget-cli

**Comment by billziss-gh** [comment]
@4O4 
> I'm starting to think it would be better if I've just removed the package and @billziss-gh you could try to add it yourself.

I could try although I might face the same problem you are facing.

Perhaps we should integrate your chocolatey scripts into this project so that I can push a new chocolatey package whenever making a new release? As an added benefit this would make the package "trusted", which would likely mean less hassle pushing updates. (Trusted packages do not have to go through regular review.)

**Comment by billziss-gh** [comment]
@Hong-Revo 
> winget

Anyone have any real world experience with winget? How well does it work? How stable is it?

**Comment by 4O4** [comment]
@billziss-gh Repo with all the content for chocolatey package is here: https://github.com/4O4/chocolatey-packages/tree/master/sshfs
Feel free to use it for official releases. I think the "trusted" status will indeed be very beneficial for the project :)

**Comment by 4O4** [comment]
I've sent a request to remove the package so that you can re-use the "sshfs" name for an official release. I'm not sure if they are willing to do that but we'll see what the answer will be. If I get a no-no from their side then I can add you as a maintainer of the package and you could try to go from there.

**Comment by 4O4** [comment]
@billziss-gh I've added you as a maintainer of the package, can you accept the request and check if everything works?

**Comment by KaliszAd** [comment]
> @Hong-Revo
> 
> > winget
> 
> Anyone have any real world experience with winget? How well does it work? How stable is it?

It seems, Chocolatey is a lot more mature. Scoop seems to be an established alternative.

What is the progress on the Chocolatey front?

**Comment by KaliszAd** [comment]
@4O4 @billziss-gh any updates?

**Comment by billziss-gh** [comment]
@KaliszAd I have absolutely no time for this right now. I am sorry.

**Comment by KaliszAd** [comment]
The package is still totally out of date.
An alternative could be the scoop-nonportable repository: https://github.com/TheRandomLabs/scoop-nonportable/blob/master/bucket/sshfs-np.json that might be easier to maintain longer term (e.g. provide a short installation description using scoop).

**Comment by alanlivio** [comment]
The package is still out of date.

**Comment by 4O4** [comment]
FYI: https://github.com/4O4/chocolatey-packages/issues/1#issuecomment-886667509

**Comment by alanlivio** [comment]
thanks @4O4.
