### ISSUE TITLE
Not able to connect after anniversary update on Windows 10

### ISSUE THREAD

**Issue by piperun** [billziss-gh/sshfs-win#2]
Beside nullifying most of my custom settings, it seems that winfsp + sshfs stopped working.

**Comment by billziss-gh** [comment]
I have not performed the update as I am on vacation and have limited time. Have you tried reinstalling/repairing WinFsp + SSHFS? I am wondering if some of the registry settings have been changed by the update.

**Comment by piperun** [comment]
I tried reinstalling WinFsp and sshfs with the same result and also as far as I know, certain registry settings has been changed.

**Comment by piperun** [comment]
Update: After repairing both SSHFS and WinFSP it seems to be working, although I am a bit cautious if anything gets screwed up.
