### ISSUE TITLE
Different permission problem (how to interpret fsptool perm results)

### ISSUE THREAD

**Issue by anttin2020** [billziss-gh/sshfs-win#212]
Hi!
I already thought my permission problems were solved but now I noticed new one.
This is related to VSCode but as this problem only occurs on SSHFS drive, it does not seem to be actual VSCode problem. Can still be, of course.
I could try to figure out the problem on my own but I have no clue what the fsptool perm output means so even if you don't have solution to this exact problem, can you please reveal the perm command output and maybe what the differences in below results mean? :)

I have this command run by Sirikali:
`"C:\Program Files\SSHFS-Win\\bin\sshfs.exe" -f --VolumePrefix=\mysshfs\"username@mysite.com;/home/username" "username@mysite.com:/home/username" "N:"  -o rw,fsname=sshfs@"username@mysite.com:/home/username",subtype=sshfs,create_file_umask=0111,create_dir_umask=0000,idmap=user,uid=-1,gid=-1,StrictHostKeyChecking=no,IdentityFile=C:/Users/username/.ssh/id_rsa,volname="username"`

For normal use it works fine, I can create folders and files with explorer and Notepad++ etc.
Also VSCode can create and edit files and folders when done by UI i.e. myself.
VSCode process is owned by me and my account belongs to Administrators:
```
C:\Program Files (x86)\WinFsp\bin>fsptool-x64 id
User=S-1-5-21-2240619032-2423407457-165706809-1002(computername\username) (uid=197610)
Owner=S-1-5-21-2240619032-2423407457-165706809-1002(computername\username) (uid=197610)
Group=S-1-5-21-2240619032-2423407457-165706809-513(computername\None) (gid=197121)
```

BUT when a VSCode extension (Local History) tries to write files, it creates subfolder .history and then writes the history files there. It works for one root-level file but when it tries to save new history version of that same file, it fails with:
`Error with mkdir: 'Error: EPERM: operation not permitted, mkdir 'n:\public_html\.history'' file 'n:\public_html\.history\index_20200622181510.html`
Same happens for any subdirs in that history folder but only succeeds when the directory does not already exist.
To me it seems that for some reason, creating file in existing directory fails but only on SSHFS, not locally. If the directory is created when creating a file in there, it works.

fsptool-x64 perm gives following results:
```
C:\Program Files (x86)\WinFsp\bin>fsptool-x64 perm n:\ (mount root)
O:S-1-5-21-2240619032-2423407457-165706809-1002G:S-1-5-21-2240619032-2423407457-165706809-513D:P(A;;FA;;;S-1-5-21-2240619032-2423407457-165706809-1002)(A;;0x1200a8;;;S-1-5-21-2240619032-2423407457-165706809-513)(A;;0x1200a8;;;WD) (perm=197610:197121:0711)
```
```
C:\Program Files (x86)\WinFsp\bin>fsptool-x64 perm n:\public_html (web root on server, not created by me but linux rights 750 and owned by me)
O:S-1-5-21-2240619032-2423407457-165706809-1002G:S-1-5-21-2240619032-2423407457-165706809-513D:P(A;;FA;;;S-1-5-21-2240619032-2423407457-165706809-1002)(A;;0x1200a9;;;S-1-5-21-2240619032-2423407457-165706809-513)(A;;0x120088;;;WD) (perm=197610:197121:0750)
```
```
C:\Program Files (x86)\WinFsp\bin>fsptool-x64 perm n:\public_html\.history (folder for history root created by VSCode Local History extension)
O:S-1-5-21-2240619032-2423407457-165706809-1002G:S-1-5-21-2240619032-2423407457-165706809-513D:P(A;;FA;;;S-1-5-21-2240619032-2423407457-165706809-1002)(A;;0x1201ef;;;S-1-5-21-2240619032-2423407457-165706809-513)(A;;0x1200a9;;;WD) (perm=197610:197121:0775)
```
```
C:\Program Files (x86)\WinFsp\bin>fsptool-x64 perm n:\public_html\tvdb (a folder created by me)
O:S-1-5-21-2240619032-2423407457-165706809-1002G:S-1-5-21-2240619032-2423407457-165706809-513D:P(A;;FA;;;S-1-5-21-2240619032-2423407457-165706809-1002)(A;;0x1200a9;;;S-1-5-21-2240619032-2423407457-165706809-513)(A;;0x1200a9;;;WD) (perm=197610:197121:0755)
```
```
C:\Program Files (x86)\WinFsp\bin>fsptool-x64 perm n:\public_html\.history\tvdb (a subfolder in history created by VSCode Local History extension. Note that on first time i.e. when the folder is created, the error occurs but the file is created. Subsequent trials to write there fail and no other files are created)
O:S-1-5-21-2240619032-2423407457-165706809-1002G:S-1-5-21-2240619032-2423407457-165706809-513D:P(A;;FA;;;S-1-5-21-2240619032-2423407457-165706809-1002)(A;;0x1201ef;;;S-1-5-21-2240619032-2423407457-165706809-513)(A;;0x1200a9;;;WD) (perm=197610:197121:0775)
```
The permission results are close to each other but not same so please tell me what those cryptic codes mean :)

Thank you very much!

Antti

**Comment by billziss-gh** [comment]
I do not have the time to look into each individual output closely, but I will explain what `fsptool perm` reports.

The first part of the output is the SDDL of the Security Descriptor of the file in question. A security descriptor basically describes who owns a file and what access users have on that file (i.e. it contains the “ACL” for that file). Searching SDDL on the net yields a few interesting links. Here is the one from Microsoft:

https://docs.microsoft.com/en-us/windows/win32/secauthz/security-descriptor-definition-language

The second part of the output (the one in parentheses) describes the UNIX permissions that the Security Descriptor is translated to. The format is UID:GID:PERM, with PERM in octal.

**Comment by anttin2020** [comment]
Thank you very much for fast reply and explanation with link, I will check those out :)
