### ISSUE TITLE
Errors while navigating on remote, bad characters

### ISSUE THREAD

**Issue by roncapat** [billziss-gh/sshfs-win#22]
I have a Home Server with a RAID5 disk mounted as _/mnt/md-name-HomeServer:0_, symlinked as _/storage_ for an easier access.

From windows 10 explorer, using sshfs-win and WinFsp, "_md-name-HomeServer:0_" is spelled as _"md-name-HomeServer0_", with the weird character having HEX representation `F03A` (converted from directory name with the help of notepad++ converter). 

This apparently causes troubles, because if I navigate _/mnt/md-name-HomeServer0/data_, I can access _/data_ subfolder, but if I go through _/storage_, I can see the data subfolder, but can't navigate inside it ("wrong syntax" error).

**Comment by roncapat** [comment]
from bash: ` xxd -pu <<< "md-name-HomeServer:0"` 
output: `6d642d6e616d652d486f6d655365727665723a300a`

**Comment by billziss-gh** [comment]
The colon (`:`) is an invalid character for a Windows file name. Invalid characters are remapped by WinFsp to the Unicode private area `0xF000`.

Having said this this mapping might not work properly when going through a symlink. Thanks for the report!

**Comment by roncapat** [comment]
Right, invalid columns in Windows are something that I should have thought
to before posting.
The latter part of your message is interesting, I didn't know about such
kind of mapping. If you do some fix and want a tester, tag me! :)

Thank you for rapid answering.

Il dom 4 feb 2018, 00:13 Bill Zissimopoulos <notifications@github.com> ha
scritto:

**Comment by billziss-gh** [comment]
Can you please open this against [WinFsp](https://github.com/billziss-gh/winfsp)? I have a suspicion that this problem is more related to WinFsp rather than SSHFS-Win.

**Comment by roncapat** [comment]
Ok, I'll do. How do I check that it is only a winfsp problem? Can I use sshfs-win driver directly from command line without winfsp?

**Comment by billziss-gh** [comment]
Sshfs-win requires a kernel-mode component, which is provided by WinFsp. There is no way around that, regardless of how you start `sshfs`.

Based on the description of your problem it just feels more relevant to WinFsp's handling of invalid file name characters, rather than anything that the SSHFS file system does.

**Comment by roncapat** [comment]
Thanks you for your clear explanation. I'll open a issue for winfsp :)

**Comment by billziss-gh** [comment]
I am closing this as it was followed up on WinFsp.
