### ISSUE TITLE
Available free space not correctly reported for mounts behind the root sshfs mount

### ISSUE THREAD

**Issue by dr-rockzo** [billziss-gh/sshfs-win#220]
If a remote sshfs mount has its own additional mounts, the free space for those additional mounts is not correctly reported.  This sometimes results in a file transfer being blocked because Windows thinks there is not enough free space available.

## Steps to Reproduce

1. Setup a Linux machine and mount a path in a separate Windows machine using sshfs-win.  Let's use the path `/mnt/root_mnt`, and say there are 10 GB of free space available at that path.
2. On the Linux machine, mount an additional drive to the path `/mnt/root_mnt/sub_mnt`.  Let's say there are 100 GB of free space available on that path.
3. Back on the Windows machine, try to copy a file larger than 10 GB to the path `/mnt/root_mnt/sub_mnt`.
4. Windows should fail to transfer the file because it's only aware of the free space available on the `/mnt/root_mnt` drive, which it thinks is 10 GB, even though the drive mounted at `/mnt/root_mnt/sub_mnt` has 100 GB of free space.

**Comment by billziss-gh** [comment]
This looks like expected behavior. The file system is only supposed to report the amount of storage that it has, not the amount of storage that may be reached via mounts, etc.

I note that in any case this is something that would be changed on the sshfs server and not on sshfs clients.

**Comment by kebien6020** [comment]
I had a similar issue to OP. If anyone else runs into this, just mapping the path to the mount (`/mnt/root_mnt/sub_mnt` in the example above) allows for correct reporting of available space.
