### ISSUE TITLE
How to specify path of id_rsa?

### ISSUE THREAD

**Issue by OpenWaygate** [billziss-gh/sshfs-win#231]
I have multiple folders in `%USERPROFILE%/.ssh/`, which contain different keys. How to specify it when connect?

```
| %USERPROFILE%/.ssh/
|  | work
|  |  | id_rsa
|  |  | id_rsa.pub
|  | personal
|  |  | id_rsa
|  |  | id_rsa.pub
```

**Comment by astadmistry** [comment]
`sshfs-win svc \sshfs.rk\root@HOSTNAME!PORT/.. G: -oIdentityFile=/c/Users/abcd/.ssh/id_ed25519 -odebug`

However do see #235

**Comment by AzureRaptor** [comment]
This isn't working for me.  I use:

>sshfs-win svc \sshfs.k\remoteusername@host!port P: -oIdentityFile=/cygdrive/c/Users/username/Documents/account_key_prv -oUserKnownHostsFile=/cygdrive/c/users/username/.ssh/known_hosts -odebug
(substituting the correct values for all "generic" parts, of course)

And I get the following output:

SSHFS version 3.5.2
executing <ssh> <-x> <-a> <-oClearAllForwardings=yes> <-oUserKnownHostsFile=/dev/null> <-oStrictHostKeyChecking=no> <-oPreferredAuthentications=publickey> <-oPort=port> <-oUserKnownHostsFile=/cygdrive/c/users/username/.ssh/known_hosts> <-2> <user@host> <-s> <sftp>
Warning: Permanently added '[host]:19678,[192.168.0.60]:19678' (ECDSA) to the list of known hosts.
Enter passphrase for key '/cygdrive/c/Users/username/.ssh/id_rsa':
Server version: 3
Extension: posix-rename@openssh.com <1>
Extension: statvfs@openssh.com <2>
Extension: fstatvfs@openssh.com <2>
Extension: hardlink@openssh.com <1>
Extension: fsync@openssh.com <1>
Extension: lsetstat@openssh.com <1>
[00001] EXTENDED
  [00001] EXTENDED_REPLY       97bytes (8ms)
[00002] LSTAT
  [00002]          ATTRS       41bytes (6ms)
[00003] READLINK
  [00003]         STATUS       32bytes (5ms)
The service sshfs has been started.
The service sshfs has been stopped.

sent:               3 messages, 65 bytes
received:           3 messages, 170 bytes
rtt min/max/avg:    5ms/8ms/6ms
num connect:        1

It never tries to use the public key I specify.  It always gives me the warning about adding a host, even though that host is already in the known_hosts file.  And it always hangs (or does _something_) right at "The service sshfs has been started.", but the drive is never created.

@billziss-gh @astadmistry   Any ideas what's going on here?

**Comment by astadmistry** [comment]
@AzureRaptor The server is actually connecting successfully. This problem is exactly like #235 
For me what worked was a reboot and then using a command prompt which is not running elevated as billziss-gh recently mentioned in #235

**Comment by roman-orekhov** [comment]
I have samish problem as @AzureRaptor: sshfs-win never tries to use the public key I specify. @astadmistry  's solution didn't help: the prompt is never elevated, rebooting did nothing.

```
  c:\Users\Roman>"c:\Program Files\SSHFS-Win\bin\sshfs-win.exe" svc \sshfs.kr\REMOTE@HOST!PORT\ -oIdentityFile=/cygdrive/c/cygwin/home/Roman/.ssh/id_rsa -odebug
SSHFS version 3.7.1
executing <ssh> <-x> <-a> <-oClearAllForwardings=yes> <-oUserKnownHostsFile=/dev/null> <-oStrictHostKeyChecking=no> <-oPreferredAuthentications=publickey> <-oPort=PORT> <-2> <REMOTE@HOST> <-s> <sftp>
Warning: Permanently added '[HOST]:PORT' (ECDSA) to the list of known hosts.
REMOTE@HOST: Permission denied (publickey).
read: Connection reset by peer
```

Specifying LOCUSER takes priority and actually passes -oIdentityFile option:
```
c:\Users\Roman>"c:\Program Files\SSHFS-Win\bin\sshfs-win.exe" svc \sshfs.kr\Roman=REMOTE@HOST!PORT\ X: -oIdentityFile=/cygdrive/c/cygwin/home/Roman/.ssh/id_rsa -odebug
SSHFS version 3.7.1
executing <ssh> <-x> <-a> <-oClearAllForwardings=yes> <-oUserKnownHostsFile=/dev/null> <-oStrictHostKeyChecking=no> <-oPreferredAuthentications=publickey> <-oIdentityFile="/cygdrive/c/Users/Roman/.ssh/id_rsa"> <-oPort=PORT> <-2> <REMOTE@HOST> <-s> <sftp>
Warning: Permanently added '[HOST]:PORT' (ECDSA) to the list of known hosts.
no such identity: /cygdrive/c/Users/Roman/.ssh/id_rsa: No such file or directory
REMOTE@HOST: Permission denied (publickey).
read: Connection reset by peer
```

I'd say unless it's officially documented how to use custom identity file the topic is far from closed...

**Comment by roman-orekhov** [comment]
What does work is specifying dummy string for LOCUSER optional argument:
`usage: sshfs-win svc PREFIX X: [LOCUSER] [SSHFS_OPTIONS]`

```
c:\Users\Roman>"c:\Program Files\SSHFS-Win\bin\sshfs-win.exe" svc \sshfs.kr\Roman=REMOTE@HOST!PORT\ X: dummy -oIdentityFile=/cygdrive/c/cygwin/home/Roman/.ssh/id_rsa
Warning: Permanently added '[HOST]:PORT' (ECDSA) to the list of known hosts.
Enter passphrase for key '/cygdrive/c/cygwin/home/Roman/.ssh/id_rsa':
The service sshfs has been started.
```
