### ISSUE TITLE
Can access from mingw64, however can not see in file explorer

### ISSUE THREAD

**Issue by astadmistry** [billziss-gh/sshfs-win#235]
When I run the below command in CMD, I can access the fs from mingw64 using `cd /g` however I can not see the fs mounted in file explorer

`sshfs-win svc \sshfs.rk\root@HOSTNAME!PORT/.. G: -oIdentityFile=/c/Users/abcd/.ssh/id_ed25519 -odebug`

How do I mount the fs so I can view it from file explorer?

**Comment by billziss-gh** [comment]
If you are mounting from a command prompt make sure that the command prompt is not running elevated. When a process is running elevated it uses a different namespace for local drives and Explorer that is not running elevated cannot access drives in it.

**Comment by astadmistry** [comment]
Thank you! Some how after a simple reboot, and using CMD non-elevated... success!!
