### ISSUE TITLE
Python [WinError 1005] The volume does not contain a recognized file system

### ISSUE THREAD

**Issue by minidron** [billziss-gh/sshfs-win#243]
If I mount through command line:

`sshfs user@host:/ x:`

In Python:
```
from nt import _getfinalpathname

_getfinalpathname('x:\\')
```

I get error:

> OSError: [WinError 1005] The volume does not contain a recognized file system.

If I mount through `net use` command, Python works without error.

**Comment by billziss-gh** [comment]
I seem to recall that `getfinalpathname` requires the file system to be mounted using the mount manager. For sshfs this would mean (untested): `sshfs user@host:/ '\\.\x:'`

**Comment by minidron** [comment]
`sshfs user@host:/ '\\.\x:'`

> SSHFS version 3.5.2
Cannot create WinFsp-FUSE file system: invalid mount point.

**Comment by billziss-gh** [comment]
BTW, the single quotes (`'`) are required only when launching from a bash prompt. If launching from a command or powershell prompt, they should be removed. Another caveat is that you need to launch the file system as Administrator in order to use mount manager mountpoints.

Having said that sshfs has not been tested with mount manager mountpoints (because it was developed before they were added to WinFsp) and may not work with them.

**Comment by minidron** [comment]
Tried with and without quote. Tried launching from a cmd, powershell and cygwin bash. The result is always:

> Cannot create WinFsp-FUSE file system: invalid mount point.

Apparently, the last version of sshfs does not support it. Are you going to add this feature?

Thanks!

**Comment by billziss-gh** [comment]
> Apparently, the last version of sshfs does not support it. Are you going to add this feature?

I am really stretched thin at the moment. Would you consider sending a PR for this?

**Comment by minidron** [comment]
After doing some research (I've never worked with the c/c++ language before), I found two places that need to be updated so that sshfs can support mount manager mountpoints:

1. **sshfs-win** Need add conditional for support `\\.\x:` pattern [sshfs.c](https://github.com/libfuse/sshfs/blob/695cd8916f0e78d28009de3ffe112b9d1a1c9e5e/sshfs.c#L3453).

2. **winfsp**. Need add conditional for support `\\.\x:` pattern [dll/fuse/fuse.c](https://github.com/billziss-gh/winfsp/blob/71995a1fcd1fc9d88bfb8ff1744b0f7a932a438c/src/dll/fuse/fuse.c#L199).

After these changes, `sshfs user@host:/ \\.\x:` working and Python `_getfinalpathname('x:')` working without error. But need to launch the file system as Administrator.

> Would you consider sending a PR for this?

I can try.

**Comment by billziss-gh** [comment]
@minidron great research especially for someone who has not worked with C before!

> winfsp. Need add conditional for support \\.\x: pattern dll/fuse/fuse.c.

Thanks for the pointer. I will look into this myself.

> sshfs-win Need add conditional for support \\.\x: pattern sshfs.c.

We can look into patching this in the upstream SSHFS, or we can add a simple patch in the [patches](https://github.com/billziss-gh/sshfs-win/blob/master/patches/) directory that does the job. Let me know which is your preferred method.

**Comment by minidron** [comment]
Thank you! These updates solved the problem.

**Comment by prodchia** [comment]
I am still having this issue. I am using sshfs-win3.5.20357 and winFSP 2021 Beta2 along with SSHFS-Win Manager 1.2.1

**Comment by Bestfast** [comment]
I still have the exact same issue

**Comment by billziss-gh** [comment]
Please make sure to mount the drives using the `\\.\X:` syntax notation. You will need to do this from an account that has Administrator privileges.

**Comment by jkw** [comment]
> Please make sure to mount the drives using the `\\.\X:` syntax notation. You will need to do this from an account that has Administrator privileges.

From a end-user perspective, this is not helpful.
I have the issue and have no idea what you talk about.

I've mounted my sshfs at N:\, I don't know much more thant that.

**Comment by koutheir** [comment]
This issue is still present when mounting a file system inside a Windows QEMU VM provided by the host through `virtiofs`. I have no idea how to mount the drive differently because it is handled transparently.
