### ISSUE TITLE
Can't specify location of private key file with `sshfs-win svc`

### ISSUE THREAD

**Issue by murchu27** [billziss-gh/sshfs-win#246]
I have a number of different private keys that I need to be able to use to connect to the remote hosts that I work on. However, the default behaviour of SSHFS-Win to use the key at `%USERPROFILE%\.ssh\id_rsa`, while sensible, makes it impossible to use multiple keys.

I understand that, by running `sshfs-win` directly, it should be possible to use SSHFS options like `IdentityFile`. However, I've only been able to get this working when launching with the `cmd` command, and not the `svc` command.

1. This works with `cmd` with the following command:

`sshfs-win.exe cmd -o IdentityFile=/cygdrive/c/Users/MMurphy/.ssh/michael michael@{host}:/home/michael Z:`

2. Using `svc`, I get an error as it tries to use the default key, ignoring the `IdentityFile` option
```
> sshfs-win svc \sshfs.k\michael@{host} Z: -oIdentityFile=/cygdrive/c/Users/MMurphy/.ssh/michael
Warning: Permanently added '{host}' (ECDSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0770 for '/cygdrive/c/Users/MMurphy/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/cygdrive/c/Users/MMurphy/.ssh/id_rsa": bad permissions
michael@{host}: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
read: Connection reset by peer
```
(btw I've intentionally left the default key with the wrong permissions so that I keep getting this output when sshfs tries to use it).

I also tried writing the path to the key as `/c/Users/MMurphy/.ssh/michael`, and `C:\Users\MMurphy\.ssh\michael`, but no joy.

If I temporarily move the key that I'm trying to use to the default location and remove the `IdentityFile` option, the `svc` command works just fine, so there's no issue with permissions or anything like that.

This isn't a dealbreaker or anything, it just seems odd that custom key locations can't be used, now that the `svc` command is able to recognize private keys at all. Or maybe I'm missing something?

P.S. Thanks to everyone who contributes to this tool, it's an absolute godsend in spite of this issue.

**Comment by kaplan2539** [comment]
@murchu27 I thought my comment to issue 155 might be interesting for you: https://github.com/billziss-gh/sshfs-win/issues/155#issuecomment-777466963

**Comment by murchu27** [comment]
@kaplan2539 sorry for the mega delay. Trying out that script that you put in that comment, and I just cannot get it to work. Every time, it simply returns `The filename, directory name, or volume label syntax is incorrect.`

```
:: Here's how I want to use it, with my key on a thumb drive
>reg_key id_rsa D:\keys\my_key
The filename, directory name, or volume label syntax is incorrect.

:: Tried using the C: drive instead, with an environment variable and with an explicit path
>reg_key id_rsa %USERPROFILE%\test\my_key
The filename, directory name, or volume label syntax is incorrect.

>reg_key id_rsa C:\Users\MMurphy\test\my_key
The filename, directory name, or volume label syntax is incorrect.

:: Also tried in an elevated prompt, same result
>reg_key id_rsa C:\Users\MMurphy\test\my_key
The filename, directory name, or volume label syntax is incorrect.
```

Any idea what might be causing that message?

**Comment by murchu27** [comment]
It's been a while now, and this issue hasn't been seen to in either of the last two releases. I've sort of given up on seeing it fixed by now.

Thankfully though, [SSHFS-Win Manager](https://github.com/evsar3/sshfs-win-manager), as of one of the latest releases, seems to finally work with all systems that I need to connect to, and is also able to use custom private key locations. Looking at the debugging output of SSHFS-Win Manager when it uses a custom location, I noticed that it is using the base `sshfs.exe` executable, rather than the `sshfs-win.exe` executable we use at the CLI

```
date: 2021-04-27T15:44:02.808Z
conntype: key-file
cmd: "C:\Program Files\SSHFS-Win\bin\sshfs.exe" michael@{host}:/home/michael/ Z: -p22 -ovolname={hostname} -odebug -ologlevel=debug1 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oidmap=user -ouid=-1 -ogid=-1 -oumask=000 -ocreate_umask=000 -omax_readahead=1GB -oallow_other -olarge_read -okernel_cache -ofollow_symlinks -oPreferredAuthentications=publickey -oIdentityFile="C:/Users/MMurphy/.ssh/michael"
```

For anyone coming across this between now and when/if the devs get around to it, I'd recommend using SSHFS-Win Manager, at least for now.

**Comment by murchu27** [comment]
Finally figured out the issue here. Over in #215, people had spotted that, whenever the `[LOCUSER]` part of the `svc` command wasn't included, the first `[SSHFS_OPTION]` would be treated as the `[LOCUSER]`. When I used @Leaveyou's workaround of writing "random_text" in place of `[LOCUSER]`, I was finally able to specify the location of my private key.

```
> sshfs-win svc \sshfs.k\michael@{host} Z: random_text -o debug -oIdentityFile=/cygdrive/c/Users/MMurphy/.ssh/michael
SSHFS version 3.5.2
executing <ssh> <-x> <-a> <-oClearAllForwardings=yes> <-oUserKnownHostsFile=/dev/null> <-oStrictHostKeyChecking=no> <-oPreferredAuthentications=publickey> <-oPort=22> <-oIdentityFile=/cygdrive/c/Users/MMurphy/.ssh/michael> <-2> <michael@{host}> <-s> <sftp>
Warning: Permanently added '{host}' (ECDSA) to the list of known hosts.
...
The service sshfs has been started.
```

So turns out `svc` is able to use a custom private key location after all. The real issue here is the fact that the first additional sshfs option gets ignored when `[LOCUSER]` is not specified. I'm going to close this issue, as #215 has already captured the need to change that.

**Comment by av930** [comment]
best solution for me.

**Comment by ba-tno** [comment]
[murchu27's solution](https://github.com/winfsp/sshfs-win/issues/246#issuecomment-841167442) works, but I also found that the `%USERPROFILE%\.ssh\config` file is actually read as well. As that often already contains the config (for use with e.g. the ssh client) that can be re-used with `sshfa-win svc` to specify a custom key.

### Simplified example

`%USERPROFILE%\.ssh\config`:

```
Host some_host
    HostName 123.456.78.5
    Port 22
    User username
    IdentityFile ~/.ssh/custom_keyfile
```

This command can then be used to mount the `some_host` server over SSH using the keyfile: 
`sshfs-win svc \sshfs.k\some_host X:`

**Comment by cosmicdan** [comment]
For posterity, this worked fine for me:

sshfs-win.exe svc \sshfs.kr\user@host.com\ H: -oPreferredAuthentications=publickey -oIdentityFile="C:/Users/cosmicdan/.ssh/user@host.com.key"
