### ISSUE TITLE
Information: A GUI tool to manage sshfs-win

### ISSUE THREAD

**Issue by mhogomchungu** [billziss-gh/sshfs-win#25]
This bug entry introduces SiriKali[1] to users of sshfs-win as a GUI tool they can use to manage sshfs-win.

Instructions on how to setup sshfs-win connections using SiriKali are found here[2].

SiriKali front page has a link to a window's installer. The installer is not signed though and expect to get a warning from windows saying the application is from an unknown publisher.

[1] https://mhogomchungu.github.io/sirikali/
[2] https://github.com/mhogomchungu/sirikali/wiki/Frequently-Asked-Questions#90-how-do-i-add-options-to-connect-to-an-ssh-server

**Comment by billziss-gh** [comment]
Thank you @mhogomchungu for your work. I will also post elsewhere about it.

**Comment by billziss-gh** [comment]
I just added information about SiriKali in the [README](https://github.com/billziss-gh/sshfs-win#gui-front-end).

**Comment by mhogomchungu** [comment]
I think you should add this[1] link to the README too because its not very obvious how to set up SiriKali to use sshfs.

[1] https://github.com/mhogomchungu/sirikali/wiki/Frequently-Asked-Questions#90-how-do-i-add-options-to-connect-to-an-ssh-server

**Comment by billziss-gh** [comment]
I have added a link to SiriKali at the top of the SSHFS-Win README. I have also added the requested link on instructions on how to setup SSHFS-Win from SiriKali.

Commit 906117d35f158be6ffa19cf2ba61b4c6cd3c37fa.

I am closing this now as there is a prominent link for SiriKali at the README.

**Comment by mhogomchungu** [comment]
Version 1.3.7 of SiriKali was just released[1]

1. This version requires sshfs-win version 3.2 or newer.

2. I have tested keepass with this version and hence its officially supported.

3. When setting a favorite entry, you will see checkbox that says "Volume does not use a password". Check this option to prevent SiriKali from generating a password prompt if the sshfs volume does not require a password because it doesn't require it or because it reads it from keepass or from an rsa keyfile.

[1] https://github.com/mhogomchungu/sirikali/releases/tag/1.3.7

**Comment by mhogomchungu** [comment]
Version 1.4.4 of SiriKali was just released and this version adds support for storing credentials securely using Windows' data protection API

Steps are documented here: https://github.com/mhogomchungu/sirikali/issues/131#issuecomment-630953600
