### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by xxtensazenxx** [billziss-gh/sshfs-win#254]
```
C:\Windows\system32>net use Z: \\sshfs\matt@192.168.1.124[\home\matt]
The password is invalid for \\sshfs\matt@192.168.1.124[\home\matt].

Enter the user name for 'sshfs': matt
Enter the password for sshfs:
System error 5 has occurred.

Access is denied.
```

I checked around the issues on github and can confirm 
1- the remote user (matt) has full read/write access to the folder (its own home folder)
2- my windows user is in the administrator group and I am running CMD as admin.

Looking for any suggestions. As I can easily log into it with the same credentials via SSH, the issue only happens in sshfs-win
 
Update:
I will legit donate if its fixed?

**Comment by x011** [comment]
I also have the same problem.
This problem seems abandoned, so don't count with too much help, as you problem figured out by now.

**Comment by billziss-gh** [comment]
@x011 

This project is open-source and freely available. You have a choice to use it or not use it. I have absolutely no obligation to fix any problem that you are having or not having. Please take your commentary elsewhere.

**Comment by xxtensazenxx** [comment]
Oh look another dev who takes his program being broken as a personal attack. Very unprofessional, even if it is open source.... There is no need to have an attitude nor anger when someone opens a issue for the project you're developing. Lol.
