### ISSUE TITLE
Upgrade all the libraries+tools to the latest version

### ISSUE THREAD

**Issue by breisig** [billziss-gh/sshfs-win#260]
I noticed the ported version of openssh, fuse and sshfs included in the current  installer are old. Can you update them to the latest version?

**Comment by billziss-gh** [comment]
Is there something specifically that you are looking for in the latest versions?

**Comment by breisig** [comment]
Current SSHFS library version
- SSHFS 3.5.2(current) -> SSHFS 3.7.1(LATEST)
 - Added a direct_io option which might help issues with some people having 0byte size issues.
 - New max_conns option enables the use of multiple connections to improve responsiveness during large file transfers. This could help with performance with people transfering large files.
- libFUSE 3.2 (Current. Over 3 years old) -> 3.10.1(Latest)
 - Fixed readdir bug when non-zero offsets are given to filler and the filesystem client, after reading a whole directory, re-reads it from a non-zero offset
 - Various minor bugfixes and improvements.
 - Various memory link
 - Performance and new features added.
- OpenSSL 1.1.1f -> 1.1.1.i
 - Never hurts to update to the latest.

**Comment by billziss-gh** [comment]
Some of these changes look legitimately good. The biggest problem is this:

- libFUSE 3.2 (Current. Over 3 years old) -> 3.10.1(Latest)

SSHFS-Win does not use libfuse, but the FUSE emulation layer included in WinFsp. So there may be some issues if we upgrade to the latest version of SSHFS-Win.

Still this may be worth for the other improvements that seem legitimate.

**Comment by billziss-gh** [comment]
@breisig 

I have pulled the latest SSHFS 3.7.1 changes in branch [sshfs-3.7](https://github.com/billziss-gh/sshfs-win/tree/sshfs-3.7). I have used these changes to produce the 64-bit and 32-bit builds found below:

- 64-bit: [sshfs-win-3.7.21011-x64.zip](https://github.com/billziss-gh/sshfs-win/files/5799251/sshfs-win-3.7.21011-x64.zip)
- 32-bit: [sshfs-win-3.7.21011-x86.zip](https://github.com/billziss-gh/sshfs-win/files/5799256/sshfs-win-3.7.21011-x86.zip)

Please try these builds and let me know if you experience any issues.

**Comment by billziss-gh** [comment]
I have now merged the sshfs-3.7 branch into master. A new beta release with latest upstream SSHFS will be released shortly.

**Comment by breisig** [comment]
ok, I will test it out!

**Comment by breisig** [comment]
Can't wait for the next sshfs release that has a fix for mkdir an existing directory [https://github.com/libfuse/sshfs/pull/242] which will help sshfs-win.
