### ISSUE TITLE
Move file between two drives on a common mount point

### ISSUE THREAD

**Issue by CatTurbo** [billziss-gh/sshfs-win#274]
Hello everybody
First a big thank to billziss-gh for the development of sshfs-win. 
During the initial testing of this fantastic piece of software I've came to a, in my opinion unexpected behaviour, which might be a bug. 
So, we have a file system consisting of two different drives which are mounted to /mnt/drive_1 and /mnt/drive_2 whereas /mnt lies on another partition of drive_1. 
I mount the mountpoint of these drive (/mnt) with sshfs-win with the following command (over the graphical user interface SSHFS-Win manager): 

`sshfs.exe" username@server:/mnt/ E: -ovolname=maindata -odebug -ologlevel=debug1 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -ocreate_file_umask=0002 -ocreate_dir_umask=0002 -oallow_other -oallow_root -ononempty -ofollow_symlinks -oPreferredAuthentications=publickey -oIdentityFile="my_key_file"`

So, now I have in explorer my new E: drive which points to the mount point. However, when I now try to move one file (e.g. /mnt/drive_1/folder_1/file) from drive_1 to drive_2 (/mnt/drive_2/folder2/file) by cut copy, I get an access error, showing me that the drive to which I want to copy has suddenly disconnected.
First, I thought that there is a problem with the file permissions, however, copy the file from drive_1 to drive_2 works without problems and the file and folder permissions are set for testing reasons to 777. Umask is set to 0002 for this user. What works is to mount both drives separately with individual mount commands, however then the move operation passes the files through my computer, which is not desired. 

Do I make a mistake in my reasoning  and mounting a mountpoint folder (/mnt) isn't possible at all or is this a bug?
Thank you very much for any help. 
Best regards
Cat Turbo

**Comment by billziss-gh** [comment]
The way you describe your setup (and if I understand it correctly) the remote /mnt file system consists of 2 different remote file systems mounted on /mnt/drive_1 and /mnt/drive_2. However when you export the /mnt directory via SSHFS this does not matter; as far as SSHFS is concerned the /mnt directory is just another directory.

So your scenario should be supported, and is in fact rather common as many SSH-exported file systems consist of multiple mounted file systems.

**Comment by CatTurbo** [comment]
Thank you very much for your fast reply. 
Yes this exactly the case, I have drive 1 mounted on /mnt/drive_1 and another, physically different drive mounted on /mnt/drive_2. 
I've tried it in the meantime again multiple times, even with different sshfs options and also with the user root. When logged in directly in the terminal I can move the files without problem, however when doing it over sshfs-win with ctrl+x and ctrl+v I will get the following error. 
![grafik](https://user-images.githubusercontent.com/41128273/109285648-a0164500-7821-11eb-889f-335cf50b904a.png)
(sorry that it is in German, it says that I do not have the needed rights, even though a direct mv operation on the server works with the same user works without problem). 

With other mount options (sorry I can't replicate them anymore, as I do not remember them), I've got the message that I need to have Windows admin rights for this operation. When I clicked on continue, Windows showed that the mounted volume disconnected. After clicking on ok, it was back there, however the file was not moved. 

Both folders, source and target and the test file have both the 777 permissions. 
Really sorry for bothering but I am at the end of my knowledge. Do you maybe know a way of how this, a move of a file between two physical disks, can be be achieved over win-sshfs? 
Another question that seemed a bit for odd is that when I duplicate a file, the file is duplicated via my computer, the read write speed matched the speed of my internet connection (about 10 MB/s) and not the max disk speed of the server hdd, which should be around 60 MB. Is that normal?
Thank you very much for answer and your effors

**Comment by CatTurbo** [comment]
I think I have maybe found the reason for this behaviour. 
As far I understand sshfs-win uses SFTP internally for the file transmission between server/ client. However, most SSH servers (including the famous OpenSSH) only implements SFTP protocol v3, which does not support to move a remote file to a different filesystem (due to using internally rename instead of mv). Also local copy is not supported.
For more information see here: [https://winscp.net/forum/viewtopic.php?t=14530 ](url) and here [https://superuser.com/questions/1166354/copy-file-on-sftp-to-another-directory-without-roundtrip](url)
Thus, this could explain my problem. Sorry for thinking that it was a bug. If you have other insights and think that my reasoning is false, please reopen this bug report.
