### ISSUE TITLE
Updated File always Modification Time April 22, 2009 Linux Side

### ISSUE THREAD

**Issue by n0risc** [billziss-gh/sshfs-win#282]
This causes issues with Apache Security, when filetimes are written earlier than original cached.

Windows 10:
WinFSP Latest
SSHFS-Win Latest 

Centos 7 Latest
fuse-sshfs.x86_64 Latest

**Comment by murchu27** [comment]
Same here. Exact modification time that gets written is `2009/04/22 - 20:24:48`. The issue happens to any file that is opened, even without making any changes. I've tried opening files in multiple editors (Vim, Notepad, Notepad++), and as soon as the file is opened this bogus modification time is written (even if I close the editor without making any changes).

Note that this issue with modification times doesn't happen when using the `net use...` or `sshfs-win svc...` connection methods, the issue only appears for me when using `sshfs-win cmd...`, or when `sshfs.exe` is used directly (which includes the use of [SSHFS-Win Manager](https://github.com/evsar3/sshfs-win-manager) or [SiriKali](https://github.com/mhogomchungu/sirikali)).

Frustratingly, the methods that are working are also the methods that don't seem to allow the use of custom private key locations (see #246). Don't know if there's anything in that?

**Comment by billziss-gh** [comment]
This problem has been fixed in the WinFsp development branch. See commit https://github.com/billziss-gh/winfsp/commit/b2e677a3d35b62ea78f5ba5c97b260f1f58c9007.

Unfortunately there is no release with the fix yet.

**Comment by murchu27** [comment]
Any estimated window for a release? I see building WinFSP needs things like VS build tools and the WDK, and I'd rather avoid using those on my work laptop (mostly because I'm running out of space...)

**Comment by murchu27** [comment]
Just installed the latest pre-release of WinFSP ([WinFsp 2021.1 Beta1](https://github.com/billziss-gh/winfsp/releases/tag/v1.10B1)), and when I use [SSHFS-Win Manager](https://github.com/evsar3/sshfs-win-manager) to connect, the modification time is correctly written. I'm gonna try out the other methods I mentioned too.

**Comment by murchu27** [comment]
Modification time was also correctly written when connecting with `sshfs-win svc...` and when using [SiriKali](https://github.com/mhogomchungu/sirikali) - success!

I'd vote to close this issue now that there's a pre-release with the fix. Or would it be more appropriate to wait for a full release?

**Comment by billziss-gh** [comment]
I will close this issue. Thanks for confirming that it works!
