### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by JonasOlson** [billziss-gh/sshfs-win#29]
I was delighted to see the prominent "choco install winfsp" button on the [WinFsp](https://github.com/billziss-gh/winfsp) page. Straight to the point! Is there any chance of getting a Chocolatey package also for SSHFS-Win? It would be so convenient.

**Comment by billziss-gh** [comment]
@JonasOlson I agree that it would be great to have one, but I do not have the time to create it. Perhaps you would consider helping?

**Comment by JonasOlson** [comment]
I see. I have no idea of how one does that, so for the time being, I'm afraid I can't be of any help.

**Comment by billziss-gh** [comment]
Understood.

Because SSHFS-Win includes an MSI installer that installs and uninstalls cleanly it should be fairly easy to create a chocolatey package. Chocolatey includes a [template](https://chocolatey.org/packages/msi.template) for wrapping MSI's as chocolatey packages. The general package creation documentation is [here](https://chocolatey.org/docs/create-packages).

**Comment by billziss-gh** [comment]
@HenrikBach1 has also asked for a chocolatey package.

Realistically this is relatively easy to do, but I am currently very busy with multiple projects and I am not sure when I would be able to do it. I would happily accept a PR that addresses this.

**Comment by 4O4** [comment]
Sounds easy, gonna help with this one

**Comment by billziss-gh** [comment]
@404 fantastic. Thank you!

**Comment by 4O4** [comment]
Done, pushed to the choco registry and waiting for tests / reviews / approvals to finish. Package ID is just `sshfs`, package sources are here: https://github.com/4O4/chocolatey-packages/tree/master/sshfs
I listed winfsp as a dependency so it is automatically installed. You'll be able to just `choco install sshfs` very soon 😄

**Comment by billziss-gh** [comment]
:tada: :tada: :tada:

Pawel, you are the man, thank you :-D

Let me know when it is done so that I can link to it from this project.

**Comment by 4O4** [comment]
It just got approved! https://chocolatey.org/packages/sshfs

**Comment by billziss-gh** [comment]
That was fast! I will change the SSHFS-Win README soon.

In other news, I have submitted a PR to sshfs with renewed support for Cygwin.

**Comment by billziss-gh** [comment]
I have added a link for the Chocolatey package at the top of the SSHFS-Win README.

I am now closing this as the issue has been resolved. Thank you again @404 for your work.

**Comment by 4O4** [comment]
FYI: https://github.com/4O4/chocolatey-packages/issues/1#issuecomment-886667509
