### ISSUE TITLE
question

### ISSUE THREAD

**Issue by AireagoirSteam** [billziss-gh/sshfs-win#3]
In the readme use say to install fuse on cygwin I was wondering how you would do that? is it possible to install fuse in cygwin without winfsp being on the windows system? Just wondering all i really require is fuse so i can use gvfs and sftp on cygwin.

also any help would be appreciated.

**Comment by billziss-gh** [comment]
A WinFsp installation is required for SSHFS-Win. SSHFS-Win does not require a separate Cygwin installation or Cygfuse.

A WinFsp installation is also required in order to use Cygfuse on Cygwin.
