### ISSUE TITLE
How to safely install sshfs-win as an existing Cygwin user

### ISSUE THREAD

**Issue by mscha** [billziss-gh/sshfs-win#31]
I've just installed sshfs-win, and I'm very happy with it, so far!
But I noticed that it installs its own copy of several Cygwin binaries, most notably cygwin1.dll.  I have my own Cygwin installation, and this may cause major issues – version conflicts, a different root and home directory depending on which copy of the dll gets loaded first, etcetera.

Is there a way to properly install sshfs-win as an existing Cygwin user?

**Comment by billziss-gh** [comment]
The SSHFS-Win installation is self contained and it should coexist with other Cygwin installations without problems. Have you found otherwise?

**Comment by mscha** [comment]
You're right, it doesn't seem to conflict.
Not sure why not, I've always learned that you shouldn't mix versions of cygwin1.dll, but I can't get a conflict, no matter what order I start things in.
