### ISSUE TITLE
Hide dotfiles

### ISSUE THREAD

**Issue by pbsds** [billziss-gh/sshfs-win#310]
Is it possible to make sshfs-win mark dotfiles as hidden?

**Comment by billziss-gh** [comment]
Yes, but not out of the box. You will have to specify the `-o dothidden` command line option.

**Comment by pbsds** [comment]
This is not possible from Windows Explorer?

**Comment by billziss-gh** [comment]
You can open the registry at the `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\WinFsp\Services\sshfs` and change the CommandLine setting to add the `-odothidden` option.

**Comment by pbsds** [comment]
Required a reboot, but it woks!
