### ISSUE TITLE
Unable to access to the remote's root / directory

### ISSUE THREAD

**Issue by Nicolas01** [billziss-gh/sshfs-win#32]
Despite what is written in the documentation I don't manage to mount the remote's root / directory using the following format:
`\\sshfs\user@host\..\..`
No error displayed, just redirected to Network.

With this format `\\sshfs\user@host\..` I got an error:

> \\\\sshfs is not accessible. You might not have permission to use this network resource.
> The Server service is not started.

I perfectly manage to access `\\sshfs\user@host`, so is there anything else to do to unblock access to the remote's root / directory?

**Comment by jackm1** [comment]
You can also **mount** the remote's root.
You cannot access the remote root via explorer as far as I can tell, but mounting it as a network drive using the provided instructions works perfectly for myself.

Would you mind trying that?

**Comment by Nicolas01** [comment]
Thanks @jackm1 , you are right, it works with the network drive.
