### ISSUE TITLE
create_umask not being taken into account

### ISSUE THREAD

**Issue by blodan** [billziss-gh/sshfs-win#321]
Hi,

I'm trying to get the umask set to 007 for new directorys/files (rwxrwx---) but for some reason all files being created uses the default rwxr-x---

I feel I'm missing something stupid here as I am specifying the -ocreate_umask flag as shown below;
`sshfs.exe blodan@172.16.0.5:/home/blodan F: -d -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -oidmap=user -ouid=-1 -ogid=-1 -oumask=007 -ocreate_umask=007 -oallow_other -o ssh_command=/usr/bin/ssh.exe`

I'm connecting from windows 10 to a ubuntu server, shouldn't this work out of the box or is this a known bug?
SSHFS version 3.7.1
WinFsp 2021

**Comment by dantam74** [comment]
I'm having trouble with the umask as well. It seems as if sshfs-win overrides whatever umask you set on the server-side. If I mount the same share with sshfs using an Ubuntu client, the umask is honored. If I do the same using sshfs-win it always creates files with only user permission (no group or other).

My samba configuration which had done the job properly before broke after a distribution update, and given the poor/scattered documentation on Samba I decided to use sshfs-win, which works great except not being able to set the umask.

https://serverfault.com/questions/228396/how-to-setup-sshs-umask-for-all-type-of-connections

@blodan, I tried your example and I can't get it working either with regards to the umask.

**Comment by billziss-gh** [comment]
@blodan 

The `create_umask` (and the more fine-grained `create_file_mask` and `create_dir_mask`) instruct SSHFS-Win what mode to use when creating new files and directories. However the server (`sshd` or similar) may or may not honor this request. I suspect you double-check the configuration of your SSH server.

**Comment by blodan** [comment]
Thanks for the response guys! 

Reading the thread above I got it working with the pam module, atleast Ubuntu seems to be ignoring whatever sshfs sends.

For anyone finding this thread;

Change `UMASK` in `/etc/login.defs`

Put this into `/etc/pam.d/common-session`;
```
session    optional     pam_umask.so
```
And you are golden, for references see @dantam74 post
