### ISSUE TITLE
Use existing cygwin environment

### ISSUE THREAD

**Issue by fakuivan** [billziss-gh/sshfs-win#33]
I use the cygwin environment to connect to ssh servers and I'd like to use that same environment for sshfs, given that most of my ssh configs (keys loaded to in ssh-agent, known_hosts, ssh_config) live there. Would it be possible to compile the project for an existing cygwin environment and mount the shares from there calling sshfs directly?

**Comment by billziss-gh** [comment]
This is possible (although not the scenario that SSHFS-Win enables).

You should be able to do it with the following steps:

- Download and install [WinFsp](https://github.com/billziss-gh/winfsp/releases).
- Install the included "FUSE for Cygwin".
- Clone this project and run the patches in the [patches](https://github.com/billziss-gh/sshfs-win/tree/master/patches) directory against the included version of SSHFS.
- Go into the sshfs directory and try `./configure` and `make`.
- You may also need additional dependencies (glib).

**Comment by fakuivan** [comment]
I've installed WinFsp from chocolatey, I don't know if that will ``Install the included "FUSE for Cygwin".``, but I get this error when running ``./configure``. 
```
configure: error: Package requirements (fuse >= 2.3 glib-2.0 gthread-2.0) were not met:

No package 'fuse' found
```
How should I proceed?

**Comment by billziss-gh** [comment]
Yes, you do need to install FUSE for Cygwin. From your Cygwin environment change into the WinFsp directory, and then

```console
$ cd opt/cygfuse
$ sh ./install.sh
```

**Comment by fakuivan** [comment]
That worked!

I'm experiencing some weirdness with file access mapping though.

A recap of the commands executed: 
```
# cd to where WinFsp is installed ("C:\\Program Files (x86)\\WinFsp" on my system)
cd opt/cygfuse
sh ./install.sh

git clone https://github.com/billziss-gh/sshfs-win.git --branch "v2.7.17334" --recursive sshfs-win && ( 
cd sshfs-win/sshfs && 
patch < ../patches/00-cygwin.patch && 
patch < ../patches/01-passwd.patch && 
autoreconf -i && 
./configure && 
make && 
cygstart --action=runas make install )

DRIVE_LETTER="W"
USER="user"
PATH="/home/$USER"
HOST="some.service"
sshfs -f -o fstypename=SSHFS -o idmap=user "${USER}@${HOST}:${PATH}" "${DRIVE_LETTER}:"
```

**Comment by billziss-gh** [comment]
Fantastic!

What is the file access mapping problem you are seeing? Usually these problems go away with `-o idmap=user` or `-o uid=-1,gid=-1`.

**Comment by fakuivan** [comment]
It works as I posted it. Setting ``-o uid=-1,gid=-1`` (or to the user ids) removes all privileges from the user, as if it were ``nobody``.

**Comment by fakuivan** [comment]
Yeah, I left it open in case you wanted to ask more about the id mapping acting weird, but I guess that's an should be a different issue. Closing this.

**Comment by fakuivan** [comment]
So I've tried to get this method to work with version ``3.5``, but I always get permission denied errors no matter what I pass as uid/gid to ``sshfs.exe``. 

These are the steps I took to compile and run ``sshfs`` on cygwin, since the last version of ``sshfs`` uses ``meson`` as its build system, I had to install that on cygwin. 
```bash
# cd to where WinFsp is installed ("C:\\Program Files (x86)\\WinFsp" on my system)
cd "C:\\Program Files (x86)\\WinFsp\\opt\\cygfuse"
sh ./install.sh

git clone https://github.com/billziss-gh/sshfs-win.git --branch "v3.5.19106" \
 --recursive sshfs-win && (
  cd sshfs-win/sshfs &&
  for patch in "../patches/"*; do patch < "$patch"; done &&
  mkdir build && cd build &&
  meson .. &&
  ninja &&
  ninja install
)

DRIVE_LETTER="W"
USER="user"
PATH_="/home/$USER"
HOST="some.service"
sshfs -f -o fstypename=SSHFS -o uid=-1,gid=-1 -o idmap=user \
  "${USER}@${HOST}:${PATH_}" "${DRIVE_LETTER}:"
```

Here's a gif showing the compile/run process and the results

![2019-07-07_22-09-41](https://user-images.githubusercontent.com/15100012/60777145-3191ea00-a107-11e9-8503-d31adfffd87c.gif)

Is this a common issue? How should I go about solving it?

**Comment by bobjiang82** [comment]
I tried to follow fakuivan's instructions with sshfs-win v3.5. I have winfsp-1.6.20027 installed.
At the ninja step, it keeps printing the messages like below,
_```
{standard input}:38446: Error: unknown .loc sub-directive `view'
{standard input}:38446: Error: unknown pseudo-op: `.lvu10608'
{standard input}:38453: Error: unknown .loc sub-directive `view'
{standard input}:38453: Error: unknown pseudo-op: `.lvu10609'
```_
and finally a build fail message.
`ninja: build stopped: subcommand failed.`
Any idea why?
Btw, the meson output is:
```
$ meson ..
The Meson build system
Version: 0.52.1
Source dir: /home/bjiang7/sshfs-win/sshfs
Build dir: /home/bjiang7/sshfs-win/sshfs/build
Build type: native build
Project name: sshfs
Project version: 3.5.2
C compiler for the host machine: cc (gcc 9.2.0 "cc (GCC) 9.2.0")
C linker for the host machine: GNU ld.bfd 2.29.1.20171006
Host machine cpu family: x86_64
Host machine cpu: x86_64
WARNING: Consider using the builtin warning_level option instead of adding warning flags by hand.
WARNING: Consider using the builtin warning_level option instead of adding warning flags by hand.
Message: Compiler warns about unused result even when casting to void
Program rst2man found: NO
Program rst2man.py found: NO
Configuring config.h using configuration
Found pkg-config: /usr/bin/pkg-config (1.6.0)
Run-time dependency fuse3 found: YES 3.2
Run-time dependency glib-2.0 found: YES 2.54.3
Run-time dependency gthread-2.0 found: YES 2.54.3
Message: rst2man not found, not building manual page.
Program utils/install_helper.sh found: YES (/home/bjiang7/sshfs-win/sshfs/utils/install_helper.sh)
Build targets in project: 3
Found ninja-1.9.0 at /usr/bin/ninja

```

**Comment by billziss-gh** [comment]
@bobjiang82 this really looks like a problem with meson/ninja or your installation.
