### ISSUE TITLE
Dot Files and hidden are visible in window machine

### ISSUE THREAD

**Issue by JackSp123** [billziss-gh/sshfs-win#334]
The linux dot files and temp files are visible in windows. Kindly let me know how to stop visible.

![image](https://user-images.githubusercontent.com/99979502/154710347-0a7d9ac7-a116-429d-9ca5-cf159ff1dcee.png)

**Comment by billziss-gh** [comment]
There is a command line option `-o dothidden` that you can use. Please see [Advanced Usage](https://github.com/billziss-gh/sshfs-win#advanced-usage) on how to use the command line.
