### ISSUE TITLE
mounting via net use broken in Windows10 build1803

### ISSUE THREAD

**Issue by pavelxkrejci** [billziss-gh/sshfs-win#34]
After the upgrade to build 1803 my usual command in the form
`net use S: \\sshfs\localuser=remoteuser@1.2.3.4!22 *`
resulted in:
> System Error 53 Has Occurred.
> The network path was not found.

Since then I am mounting via this cmd script:
> taskkill /F /IM "sshfs.exe"
> cd "C:\Program Files (x86)\SSHFS-Win\bin"
> set CYGFUSE=WinFsp
> set "PATH=C:\Program Files (x86)\SSHFS-Win\bin;%%PATH%%"
> sshfs remoteuser@1.2.3.4: S: -oidmap=user -oPort=22 -orellinks -ofstypname=SSHFS --VolumePrefix="\sshfs\remoteuser@1.2.3.4" -ofollow_symlinks

This workaround has also [problem](http://www.winability.com/how-to-make-elevated-programs-recognize-network-drives/) in default Windows config with separate management of network drives for normal and elevated processes.

**Comment by billziss-gh** [comment]
It may be that the upgrade overrode some registry settings. One suspicion is that it overrode the WinFsp Network Provider registry setting.

Can you please run the `diag.bat` batch file in `\Program Files (x86)\WinFsp\bin` and report the output here?

**Comment by pavelxkrejci** [comment]
Thanks, you are right, the WinFSP.np network provider is MIA.
[diag.1803.log](https://github.com/billziss-gh/sshfs-win/files/2074009/diag.1803.log)

**Comment by billziss-gh** [comment]
Always nice to have Windows upgrades mess up your system :-\

Try running the WinFsp installer and choose repair. I suspect this should fix it. If not, uninstalling and reinstalling the WinFsp installer should definitely do it.

**Comment by pavelxkrejci** [comment]
Windows 10 upgrades... thats just "no comment".
I fixed it by hand, no restart necessary. Thanks again.

imported:
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinFsp.Np\NetworkProvider]
>"Name"="Windows File System Proxy"
>"ProviderPath"="C:\\Program Files (x86)\\WinFsp\\bin\\winfsp-x64.dll"

added WinFsp.Np to ProviderOrder:
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order]
"ProviderOrder"="RDPNP,LanmanWorkstation,webclient,WinFsp.Np"

**Comment by billziss-gh** [comment]
Great. Although I would recommend `WinFsp.Np` to be the first Network Provider, if you want your SSHFS mounts to happen fast.

WinFsp takes a very quick look at an in-memory table to decide whether to handle a particular UNC prefix. So you can safely put it first. If you put it last the Windows networking components might start trying to resolve for an "SSHFS" server and things will start slowing down (although they will still work).

In any case I am closing this as it seems to have been resolved.
