### ISSUE TITLE
Inconsistent location of the registry values between 32 bit and 64 bit installers

### ISSUE THREAD

**Issue by mhogomchungu** [billziss-gh/sshfs-win#38]
```sshfs-win-2.7.17334-x86.msi``` installer creates the registry key at "SOFTWARE\\WOW6432Node\\SSHFS-Win" but ```sshfs-win-2.7.17334-x64.msi``` installers creates the registry key at ""SOFTWARE\\SSHFS-Win" , why the inconsistency?

Because of this, SiriKali fails[1] to find sshfs if its installed using 64 bit installer and i just found out about this now. It took me a while to figure out why things fail now since i was certain things works last time i used sshfs with SiriKali.

[1] https://github.com/mhogomchungu/sirikali/blob/5019cf70fd8a086062cb153a922197e908e4011c/src/winfsp.cpp#L174

**Comment by billziss-gh** [comment]
This is something that is imposed by Windows. On a 64-bit system, a 32-bit application has only access to the 32-bit part of the registry (I.e. `Wow6432Node`)

**Comment by mhogomchungu** [comment]
I am neither a windows user nor a developer so, help me out here, are the above statements correct?

1. 32 bit binaries use ```SOFTWARE\WOW6432Node\SSHFS-Win``` path on 64 bit windows.
2. 32 bit binaries use ```SOFTWARE\SSHFS-Win``` path on 32 bit windows.
3. 64 bit binaries use ```SOFTWARE\SSHFS-Win``` path on 64 bit windows.

So, a solution is to check for both paths? What other path if any should i also check?

**Comment by mhogomchungu** [comment]
Thanks for your suggestion, i fixed the issue with this[1] commit.

[1] https://github.com/mhogomchungu/sirikali/commit/c403ebadaeb9fd66b77056469547903548f89962
