### ISSUE TITLE
Request For Comments: add nsswitch.conf

### ISSUE THREAD

**Issue by billziss-gh** [billziss-gh/sshfs-win#43]
SSHFS-Win was conceived as a simple way to map SSHFS drives through explorer (using the `\\sshfs\user@server` syntax).

However I am finding that a lot of people want to run SSHFS through the command-line but they often hit the roadblock that the minimal Cygwin environment included with SSHFS does not includes support for home directories.

One simple solution might be to include an `/etc/nsswitch.conf` file with the following contents:

```
db_home: windows
```

This will make the user's Windows home directory (usually `C:\Users\USER`) into his/her SSHFS-Win home directory and will alleviate some of the discussed problems.

What do you guys think?

**Comment by 4O4** [comment]
I was thinking about something similiar recently - just setting the `$HOME` to point to windows userprofile dir - although I wasn't really sure if it would be enough. `nsswitch` looks like a much better solution. +1

**Comment by billziss-gh** [comment]
@4O4 thanks. I am inclined to add this to the next release (that will also sync with upstream sshfs).

Ping @xelra and @mhogomchungu who may also have an interest.

**Comment by mhogomchungu** [comment]
I think its a very good idea. 

I am not very comfortable with SiriKali silently not checking of remote server signature and not giving its users the ability to manually check the signature cancel the attempt to connect when they found out remove signature is not what they expect.

**Comment by billziss-gh** [comment]
Added in commit b5f39a9b1a4032ce11755eea9fb964131265f08a.

**Comment by billziss-gh** [comment]
A beta release that updates the included SSHFS to the upstream version (3.2) and also includes this change is now available. Please report any problems:

https://github.com/billziss-gh/sshfs-win/releases/tag/v3.2.18213

**Comment by sganis** [comment]
Very good addition! I had a number of bugs to report related to ssh and key authentication, but this release fixed all my ssh issues. Thanks.

**Comment by billziss-gh** [comment]
Thanks everyone for your comments. I am closing this the `nsswitch.conf` file has been added to the latest beta.

**Comment by sganis** [comment]
I would be nice if you can update the current 2.7 release with this feature, I am adding it manually after installation for my ssh key authentication setup. 
I can't use the beta version for the time being, it was unstable in my initial testing.

**Comment by xelra** [comment]
I'm late to the party, but I think this is a great feature.

**Comment by mhogomchungu** [comment]
![screenshot 1](https://user-images.githubusercontent.com/3496115/44949673-e4861d00-ae3e-11e8-8d56-8665d5ac9861.png)

Just tested the beta version and SiriKali now works correctly with it since since sshfs-win no longer hangs when it couldn't write to .ssh folder and the folder is now correctly created in user's home directory.
