### ISSUE TITLE
How use id_rsa private key

### ISSUE THREAD

**Issue by 07pepa** [billziss-gh/sshfs-win#55]
Hello there there is not documented how use id_rsa key with combination of password... or it does not work yet..

**Comment by tsauri** [comment]
#1 
Try follow my instruction but input your password also

**Comment by 07pepa** [comment]
I will try it when I will have access to server again.. it does work I suggest putting this in the documentation.

**Comment by 07pepa** [comment]
geting error 

Failed To Complete The Task And Below Log was Generated By The Backend.

----------------------------------------

**Comment by 07pepa** [comment]
and there is no log

**Comment by stefan-muc** [comment]
``sshfs -o IdentityFile=/path/to/key server:/ x:`` 

and yes, the IdentityFile option is missing in help

Make sure path to sshfs bin directory is in PATH otherwise sshfs will output "read: Connection reset by peer" which in detail means "failed to execute 'ssh': No such file or directory"

**Comment by stefan-muc** [comment]
Oh and by the way: If you seem to have problems with user rights use ``-o uid=-1``
I had problems accessing files that only my user (not my group) was allowed to access, this option fixed it.
