### ISSUE TITLE
Feature request: mount root path by default

### ISSUE THREAD

**Issue by sganis** [billziss-gh/sshfs-win#56]
This is related to issue #12 and probably #5, #27, and #37 too. 

`sshfs-win.exe` creates a `sshfs.exe` call with arguments. The problem appears when we use double slashes to mount the root path like `user@host\\path`. 

From command line, `> net use z: user@host\` translates to `user@host:` and mounts the home directory, `> net use z: user@host\\` translates to `user@host:/` and mounts the root path, but using the network mapping drive form windows explorer, double slashes are transformed into one which translates into `user@host:` and mounts the home directory, which is not the user's intention and that creates all the confusion. Windows is to blame here, double black slashes are not interpreted consistently with different apps. 

The solution is to mount the root path by default to make the mounting path consistent. Anyone using this technology is already familiar with the Linux file system and this change will remove the current friction. Even if a user needs to mount the home directory and has zero knowledge of Linux, the home full path can be provided by some IT support.

In the table below, row 3 and 4 are the problem, so the user has to rely on something like `user@host\..\..\..\..\` to mount the root path. The problem is eliminated with the proposed solution. 

|Row | sshfs-win.exe args  | translates into | mounts to | should translate into |
|---:| -------------       |---------------| ----------| ----------|
|1   | `user@host`         | `user@host:` | `$HOME`   | `user@host:/` |
|2   | `user@host\`        | `user@host:` |`$HOME`    | `user@host:/` |
|3   | `user@host\\`       | `user@host:/` if net use, but <br> `user@host:` if map drive |`/` if net use, but <br> `$HOME` if map drive | `user@host:/` |
|4   | `user@host\\path`   | `user@host:/path` if net use, but <br> `user@host:path` if map drive | `/parh` if net use, but <br> `$HOME/path` if map drive |`user@host:/path` |
|5   | `user@host\\\\\`    | `user@host:///` | `/` | `user@host:///` |
|6   | `user@host\..\`     | `user@host:../` |   `$HOME/..`|`user@host:/../` |

To implement this solution, just replace line 78 in sshfs-win.c by this block and `#include <string.h>`:

```c
    path = p;

    /* mount root by default, prepend a slash before path if needed */
    if (*p != '/')
    {
        char s[256];
        strcpy(s, "/");
        strcat(s, p);
        path = s;
    }
```

I was planning to send a pull request, but I don't know how to send this small code without sending too many changes in my branch.

**Comment by limeb** [comment]
This is a really good idea.

**Comment by billziss-gh** [comment]
@sganis I finally looked into your request in more detail.

I do not necessarily agree that root should be the default mounted directory, although I do agree that mounting on the root directory should be easier.

Perhaps one way would be to register SSHFS-Win under two prefixes: `\\sshfs` and `\\shhfs.r`. The first one acts as it does today. The second mounts under root by default.

**Comment by mattaw** [comment]
Love the idea, please implement.

**Comment by billziss-gh** [comment]
The latest SSHFS 3.5 BETA includes support for `\\sshfs.r`. Get it [here](https://github.com/billziss-gh/sshfs-win/releases).

**Comment by Helvio88** [comment]
All I did was:
\\sshfs\user@server\/
to mount the root.

**Comment by Kyogre** [comment]
```
All I did was:
\\sshfs\\user@server\/
to mount the root.
```
But to unmount such network drive you will need to execute such two commands manually:
```
net use Z: /del
net use \\sshfs\\user@server\/ /del
```

Thus it is not so good as `\\sshfs.r\\user@server`
