### ISSUE TITLE
terribly slow when doing dir listings using /bin/ls in cygwin

### ISSUE THREAD

**Issue by riedel** [billziss-gh/sshfs-win#6]
Probably not really an sshfs bug but a cygwin problem.

I am actually disabling all -l options and colors. Still takes quite a long time.

It is really strange. Native windows `dir ` is expectedly (by far!?) the fastest. 

However, while normal  `ls `on cygwin via smb is faster, a ` ls -l` performs faster when run via sshfs then via smb (cygwin opens the files here).

I simply don't get it why cygwin ls is so inferior (4x) on sshfs for normal cygwin readdir calls. The problem is that this makes anything (tab completion, etc.) slow.

```
> sshfs.exe -ofstypename=SSHFS -o idmap=user -o umask=000  -o Ciphers=aes128-gcm@openssh.com -o Compression=no user@smbsrv: x:

>time \ls  /mnt/x/bin >/dev/null

real    0m6.103s
user    0m0.000s
sys     0m0.031s


>time \ls  //smbsrv/bin >/dev/null

real    0m1.794s
user    0m0.015s
sys     0m0.046s

>time \ls -l //teco141pc/riedel/bin >/dev/null

real    0m32.162s
user    0m0.000s
sys     0m0.108s

>time \ls -l /mnt/x/bin >/dev/null

real    0m28.309s
user    0m0.046s
sys     0m0.093s

>time cmd /c dir x:\bin >/dev/null

real    0m0.789s
user    0m0.000s
sys     0m0.000s

>time cmd /c dir '\\smb\bin'  >/dev/null

real    0m0.576s
user    0m0.000s
sys     0m0.015s

```

Any ideas how to speed things up?

**Comment by riedel** [comment]
I actually found a work around.

Using the ihash option in cygwin mount makes it really fast.

The documentation speaks about broken filesystems, so I leave this issue open.

**Comment by billziss-gh** [comment]
Very interesting.

When Windows enumerates directories it returns full information about a file. This includes information about its file name and its metadata (`WIN32_FIND_DATA` - file name + stat information).

Cygwin `ls` is a POSIX program which means it must use `readdir` to list a directory. `Readdir` returns a list of `dirent` which only contain information about the file name, the file i-node number and possibly the file type (directory, file, etc).

This means that Cygwin `ls -l` has to do `readdir` and then `stat` for each individual file. This may explain the huge time difference between:

    >time \ls  /mnt/x/bin >/dev/null
    
    real    0m6.103s
    user    0m0.000s
    sys     0m0.031s

and:

    >time \ls -l /mnt/x/bin >/dev/null
    
    real    0m28.309s
    user    0m0.046s
    sys     0m0.093s

It is harder to explain the difference between `ls` without the `-l` option and `cmd /c dir`.

    >time cmd /c dir x:\bin >/dev/null
    
    real    0m0.789s
    user    0m0.000s
    sys     0m0.000s

BTW, have you tried to time `ls /cygdrive/x/bin`?

One idea here is to run `sshfs` with an `attr_timeout` of 1 second (`-oattr_timeout=1`). This should cache file metadata for 1 second thus speeding up a lot of these queries as they are now satisfied from cached metadata in the kernel. If `attr_timeout` does not work try `-oFileInfoTimeout=1000`, which is the WinFsp-FUSE equivalent option.

> Using the ihash option in cygwin mount makes it really fast.

Interesting. It may be that SSHFS simply returns bogus i-node numbers. I will investigate this a bit further to make sure that it is not the WinFsp-FUSE layer that messes up.

**Comment by riedel** [comment]
Sorry, I forgot to say: I remapped /cydrive to /mnt in fstab (to align it with WSL)

Setting the timeout does not give significant speedup (the variance is bigger than the potential speedup of 10%=0.5s I saw)

What you describe aligns with what I thought.

BTW: interestingly the (re-)setting of the related option "readdir_ino" and "use_ino" also makes no change

**Comment by billziss-gh** [comment]
If you have time to retest this, download the latest version of WinFsp. There have been some significant improvements in the WinFsp FUSE layer which SSHFS-Win uses.

**Comment by billziss-gh** [comment]
Closing as I believe this is now addressed. Reopen if you think otherwise.
