### ISSUE TITLE
"sshfs.exe --version" command reports wrong version

### ISSUE THREAD

**Issue by mhogomchungu** [billziss-gh/sshfs-win#76]
I installed version ```SSHFS-Win 3.2 BETA``` and ```sshfs.exe --version``` produced below output
```
C:\Program Files\SSHFS-Win\bin>sshfs.exe --version
SSHFS version 3.4.0
FUSE library version 3.2

C:\Program Files\SSHFS-Win\bin>
```

**Comment by billziss-gh** [comment]
Thanks for report. I suspect that the `sshfs --version` report is correct and the beta version used is actually wrong, but will investigate before making a final release.

**Comment by billziss-gh** [comment]
I am updating SSHFS-Win to latest upstram (3.5.2) and this problem should no longer be relevant. 

Closing. Thanks again for report.
