### ISSUE TITLE
sshfwin crashes randomly

### ISSUE THREAD

**Issue by shayaantx** [billziss-gh/sshfs-win#77]
Hello,

Occasionally my sshfs mapped drive crashes and becomes unavailable. Below is the stack dump.

Every time this occurs I have to remap the drive, below is also the command I use for the mapping. I've done the mapping with my local admin user and the local system user, the crash occurs regardless, and never persists. I included the wmic netuse results as well, below the stack dump

Any ideas? Are there any logs I can look at?

net use x: \\sshfs\USERNAME@HOSTNAME!PORT\\\\ "PASSWORD" /persistent:yes

Exception: STATUS_ACCESS_VIOLATION at rip=001800BEAC7
rax=0000000000000000 rbx=0000000000000000 rcx=0000000000002000
rdx=0000000000000000 rsi=0000000000000000 rdi=0000000000000000
r8 =0000000000010000 r9 =0000000000000001 r10=00000000041F0000
r11=0000000000000000 r12=00000000041EBEB1 r13=0000000000000007
r14=00000000041EC510 r15=0000000000000001
rbp=00000000041EBEB0 rsp=00000000041EBE68
program=C:\Program Files\SSHFS-Win\bin\sshfs.exe, pid 16044, thread unknown (0x3FC0)
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
000041EBEB0  001800BEAC7 (000041EBE9F, 0000000EA60, 0018012F454, 0018030D588)
000041EBEB0  00100401899 (001802E5EA0, 0017C0F8690, 0018024D640, 000041EC511)
001802E45A0  00100402CC5 (00000000048, 00000000001, 000041EC2F0, 00000000007)
00000000001  001004045D6 (00000000080, 0060130D750, 7FFE8960878A, 00000000060)
00000000001  0010040483D (00180118AFB, 00000000000, 006032F5B60, 00000000000)
000041EC320  001004054E5 (006032F5B60, 000041EC511, 8080808080808080, 006032E9D40)
000041EC3E0  0010040617A (00000000040, 000026E0000, 7FFE8B747AD6, 00000000040)
000041EC471  0010040A38E (34002E00000002, 39003400000080, 39003200370036, 00000000000)
000041EC471  7FFE7E4B3B88 (00002708880, 00000000000, 00000000000, 000041EC504)
00002722588  7FFE7E4B6126 (00002708880, 00002722588, 00000000003, 00000000000)
000001F0000  7FFE7E4C1C80 (00002726500, 00002716480, 00000000000, 00000000268)
00002716480  7FFE7E4C1DE6 (000FFFFFFFF, 00002726500, 000FFFFFFFF, 00002722530)
00002716480  7FFE7E4C37A1 (00000000000, 000000002D8, 7FFE7E4C35A0, 00000000000)
00002716480  00180045693 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180045744 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  7FFE8B721FE4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace (more stack frames may be present)

C:\WINDOWS\system32>wmic netuse
AccessMask  Caption              Comment  ConnectionState  ConnectionType         Description                                      DisplayType  InstallDate  LocalName  Name                                                       Persistent  ProviderName               RemoteName                                            RemotePath                                            ResourceType  Status       UserName
1179785     RESOURCE REMEMBERED           Disconnected     Persistent Connection  RESOURCE REMEMBERED - Windows File System Proxy  Share                     x:         \\sshfs\USERNAME@HOSTNAME!PORT\\\\ (x:)  TRUE        Windows File System Proxy  \\sshfs\USERNAME@HOSTNAME!PORT\\\\  \\sshfs\USERNAME@HOSTNAME!PORT\\\\  Disk          Unavailable
1179785     RESOURCE CONNECTED            Disconnected     Current Connection     RESOURCE CONNECTED - WinFsp.Np                   Share                     X:         \\sshfs\USERNAME@HOSTNAME!PORT (X:)      FALSE       WinFsp.Np                  \\sshfs\USERNAME@HOSTNAME!PORT      \\sshfs\USERNAME@HOSTNAME!PORT      Disk          Unavailable

**Comment by Sh4rK** [comment]
Hi, I also experience crashes with the currently latest [WinFSP](https://github.com/billziss-gh/winfsp/tree/v1.5B1) + [sshfs-win](https://github.com/billziss-gh/sshfs-win/tree/v3.2.18213).

The command I used to run sshfs:
```
sshfs user@host: T: -d -o gid=-1 -o uid=-1
```

The exception:
```
Exception: STATUS_ACCESS_VIOLATION at rip=001800BE3A7
rax=000006FE7FD20010 rbx=0000000600121E50 rcx=000000003001D7F5
rdx=00000001802DBFA8 rsi=00000006001F0000 rdi=000006FE7FF10010
r8 =000006F87FD20010 r9 =00000001802DFFE0 r10=0000000003CF0000
r11=00000001004014C1 r12=00000000000000A0 r13=000000000073EE60
r14=0000000003CECA30 r15=0000000000000000
rbp=0000000000000000 rsp=0000000003CEC778
program=C:\Program Files\SSHFS-Win\bin\sshfs.exe, pid 14440, thread
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
00000000000  001800BE3A7 (00003CEC7D0, 00180140131, 00180141CFF, 006001DEDE8)
00000000000  0010040600B (00600077C60, 006000FE8A0, 001800BA6D3, 006000FE8A0)
00003CEC8A0  0010040A04E (0010040528C, 00000000005, 000000002EA, 00000000A02)
00003CEC991  7FF8A34B2E2C (00003CECA30, 00000000000, 006000FE8A0, 00000000000)
00003CEC991  7FF8A34B5E4F (00600080630, 00000000000, 00003CECA24, 00003CECA2C)
00003CECAA1  7FF8A34B6A1A (000007ADE70, 00000000001, 00000000000, 00000000010)
00003CECB79  7FF8A34C3778 (000000000A0, 000007ADE70, 00000100001, 000007ADE70)
0000073EE60  7FF8A34C4899 (00000000000, 000007B1E40, 000002C2E7C, 000007ADE70)
0000073EE60  7FF8A34C7201 (00000000000, 000000000A0, 7FF8A34C7000, 00000000000)
0000073EE60  00180045653 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180045704 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  7FF8CD8D81F4 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  7FF8CDD1A271 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
```

I use the latest beta versions because older versions do not work for me: It seems like the remote drive can be mounted, nut I have no permission to access it.

**Comment by xnoreq** [comment]
See #54

**Comment by billziss-gh** [comment]
Please try the latest version of [WinFsp (2019.3 B2)](https://github.com/billziss-gh/winfsp/releases) and [SSHFS-Win](https://github.com/billziss-gh/sshfs-win/releases) where I believe this problem has been fixed.

I am closing this. Please reopen if you find that the problem persists.
