### ISSUE TITLE
Mount Remote Director to Windows Drive fails

### ISSUE THREAD

**Issue by gatorback** [billziss-gh/sshfs-win#83]
Details documented at: https://superuser.com/questions/1423371/sshfs-remote-directory-mounting-syntax

A Windows-10 64-bit PC was outfitted with:

    winfsp-1.4.19049.msi
    sshfs-win-2.7.17334-x64.msi on Github: SSHFS-Win Github: =>

A remote linux directory (mydirectory) is to be mounted to S:. The syntax is documented here

"Baby steps" indicating preliminary success (non-Admin CLI):

net use S: \\sshfs\user@hostname.com\..\..

however this does not mount mydirectory

Other user's attempts to mount target directory have failed. Attempt from the Admin command-line failed:

net use S: \\sshfs\user@hostname.com\\mnt\MOUNTPOINT\mydirectory

System Error 67 has occured. The network name can not be found

Other failures:

net use S: \\sshfs\user@hostname.com\mnt\MOUNTPOINT\mydirectory
net use S: \\sshfs\user@hostname.com:\mnt\MOUNTPOINT\mydirectory

for some reason, the syntax is such that I am required to type the username and password despite inputting the username: user@hostname

    What is the correct syntax to mount mydirectory to the S: drive?
    What diagnostics can be performed to determine corrective action?

**Comment by billziss-gh** [comment]
Sorry for the long delay in responding. I just returned from vacation.

Here is an example use:

```
billziss@WINDOWS C:\Users\billziss
$ net use X: \\sshfs\billziss@mac2018
The password is invalid for \\sshfs\billziss@mac2018.

Enter the user name for 'sshfs': billziss
Enter the password for sshfs:
The command completed successfully.


billziss@WINDOWS C:\Users\billziss
$ x:

billziss@WINDOWS X:\
$
```

(This is on a default ConEmu console which is why the console prompts look weird. The console is running cmd.exe however.)

Notice the use of the double backslash (`\\`) when using `net use`.
