### ISSUE TITLE
Trouble while mapping network drive in Windows from Linux

### ISSUE THREAD

**Issue by vlukyanets** [billziss-gh/sshfs-win#88]
When try to map network drive on Windows 10, I have such message in `auth.log` on Linux remote side:

`input_userauth_request: invalid user \\320\\241\\320\\230\\320\\241\\320\\242\\320\\225\\320\\234\\320\\220`

It causes error, but I input correct login & password. Command-line invoking `sshfs.exe` works correctly
PC: Windows 10 x64; remote PC: Ubuntu 16.04 x64; WinFSP: 1.4.19049; SSHFS: 3.5.19106

**Comment by billziss-gh** [comment]
This almost looks like the username is translated to octal.

Can you show what the actual path that you map from Explorer is?

**Comment by vlukyanets** [comment]
\\sshfs\localhost!10002\home\valentin

Port 10002 mapped from VirtualBox. Login & password entered in special window. BTW I tried with different logins, but octal sequence didn't change.

**Comment by billziss-gh** [comment]
I am assuming that both your Windows and Linux user names are `valentin` with ASCII characters. Is that correct?

If your user name does not contain any non-ASCII characters I find this problem rather perplexing.

**Comment by vlukyanets** [comment]
Yes, it's correct. Only ASCII characters

**Comment by billziss-gh** [comment]
This sounds like a configuration issue with sshd on the remote side. SSHFS-Win does not do any character translation on user names.

**Comment by vlukyanets** [comment]
Is it possible that Windows 10 do something wrong?

**Comment by pavelxkrejci** [comment]
The octal sequence is utf-8 encoded cyrillic system account name "СИСТЕМЕ", so the account name is not translated, but completely replaced. If it is even the proper log entry. Maybe some error with wrong user id mapping.
Valentin, can you add your username as prefix like this?
`\sshfs\valentin@localhost!10002\home\valentin`

**Comment by billziss-gh** [comment]
@pavelxkrejci great catch!

**Comment by vlukyanets** [comment]
@pavelxkrejci Yes, I tried both specify username in path and specify username in modal window. Both ways fails with such problem

**Comment by billziss-gh** [comment]
Is `СИСТЕМЕ` the "SYSTEM" (or "LocalSystem") account in Cyrillic Windows?

Normally SSHFS-Win runs the sshfs file system under the SYSTEM account. But this should not affect the name used to authenticate with the SSHFS server.

**Comment by pavelxkrejci** [comment]
Maybe wrong authentication method is used via GUI. More info from more verbose server log would be helpful.
Ie. after setting LogLevel to DEBUG in your sshd_config.
See (https://ubuntuforums.org/showthread.php?t=1253064) for details.
