### ISSUE TITLE
Error Creating folder

### ISSUE THREAD

**Issue by zhu-ty** [billziss-gh/sshfs-win#90]
When I try  to create a folder in Mounted FileSystem, I get this:
![20190514153041](https://user-images.githubusercontent.com/8665404/57679273-79dbe100-765d-11e9-9fb5-c1efdbcecf35.png)
Does anyone know what's going on?

**Comment by xnoreq** [comment]
Duplicate of #54

**Comment by billziss-gh** [comment]
Please try the latest version of [WinFsp (2019.3 B2)](https://github.com/billziss-gh/winfsp/releases) and [SSHFS-Win](https://github.com/billziss-gh/sshfs-win/releases) where I believe this problem has been fixed.
