### ISSUE TITLE
Windows: no writing rights for ordinary user

### ISSUE THREAD

**Issue by dominik-d** [billziss-gh/sshfs-win#91]
Hello, I am using Centos 7, sshfs-win-2.7.17334-x64, winfsp-1.5.19090. 
Mapping a home dir of an ordinary user - no way to get writting rights (file will be created, but 0 size and 'access denied' from windows comes up).
This does not happen for user root (writing files possible).
-o sshfs_sync does not solve the issue.
I had no problem to transfer files using WinSCP with ordinary user logged in.

Ordinary user:
C:\Program Files\SSHFS-Win\bin>sshfs.exe -o fstypename=SSHFS -o create_umask=000 -o umask=000 -o allow_other tomas@HOST: s:
C:\Program Files (x86)\WinFsp\bin>fsptool-x64.exe perm s:\nova.jpg
O:S-1-0-65534G:S-1-0-65534D:P(A;;0x1f01bf;;;S-1-0-65534)(A;;0x1201af;;;S-1-0-65534)(A;;0x1201af;;;WD) (perm=65534:65534:0777)

Root user:
C:\Program Files\SSHFS-Win\bin>sshfs.exe -o fstypename=SSHFS -o create_umask=777 -o umask=000 -o allow_other root@HOST: g:
C:\Program Files (x86)\WinFsp\bin>fsptool-x64.exe perm g:\nova.jpg
O:BAG:DUD:P(A;;0x1f01bf;;;BA)(A;;0x1201af;;;DU)(A;;0x1201af;;;WD) (perm=544:1049089:0777)

**Comment by billziss-gh** [comment]
If you are using this from the command line make sure you pass the `-o uid=-1,gid=-1` option to make files accessible to the user who launched the file system.

**Comment by dominik-d** [comment]
Thanks, but the option `-o uid=-1,gid=-1` does not solve the problem. Using it or not, the 'copy' result is the same:
-rwx------.  1 tomas tomas        0 May 20 02:05 file1.jpg
The file was created by a correct user, but for some reason, it cannot be written.
Following acces rights were created when the option  `-o create_umask=000` is used:
-rwxrwxr-x.  1 tomas tomas        0 May 20 02:18 file2.jpg
Is there a way how to force the driver to create a '777' file?

**Comment by billziss-gh** [comment]
As far as Windows is concerned it thinks that the permissions are `0777` (i.e. `rwx` for all) and should allow access. Is there perhaps some setting on your SSHFS server that prohibits users other than `root` from getting proper permissions?

It looks to me that permissions are correct, because of this  excerpt from your first post: `(perm=65534:65534:0777)` after running `fsptool perm`. (If you pass the option `-o uid=-1,gid=1` you should also see the correct UID,GID being calculated in the output.)

**Comment by dominik-d** [comment]
You are right, the problem was in the copy method. While testing I was always using Total Commander to copy the files. The method used by default seems to cause problems (only for non-root user). Thanks a lot for your support.

**Comment by billziss-gh** [comment]
I am glad this worked for you in the end. Closing this.
