### ISSUE TITLE
Whos username and password to enter sshfs ?

### ISSUE THREAD

**Issue by Sulistyarif** [billziss-gh/sshfs-win#96]
C:\Users\Sulis>net use X: \\sshfs\192.168.100.180
The password is invalid for \\sshfs\192.168.100.180.

Enter the username for 'sshfs': fam
Enter the password for sshfs:
System error 5 has occurred.

Access is denied.

So, whose username that i must write ? my server username ? my samba username ? or my windows 10 username ?

**Comment by billziss-gh** [comment]
As per the README the syntax is: `\\sshfs\REMUSER@HOST[\PATH]`. So you must use the username and password for the remote user (i.e. server user).

**Comment by joe733** [comment]
Hi,

I'm trying to have a `shared folder` between a Linux and Windows desktop. My aim is to:

1. Map a Linux folder (with rwx)  `/home/$USER/Public` to Windows `Z:` drive. Or..
2. Mount a Windows folder (with wx) `D:\Shared` on  `/home/$USER/Public/Shared`

Here's what I did, for **1**:

- On Linux: I installed [`sshfs`](https://archlinux.org/packages/?name=sshfs). *Is there anything to be configured after installation, here?*
- On Windows: I installed [`WinFsp`](https://github.com/billziss-gh/winfsp/releases/tag/v1.10B2) and [`SSHFS-Win`](https://github.com/billziss-gh/sshfs-win/releases/tag/v3.7.21011). Then according to [the instructions](https://github.com/billziss-gh/sshfs-win#basic-usage) I tried `\\sshfs\\$USER@hostname\home\$USER\Public` but it keeps showing me this:

![image](https://user-images.githubusercontent.com/38415384/126160676-028dc4c3-13f8-4be9-b424-6f9fd88b2a43.png)

For **2**:

- I'm not sure what to do (w/o samba), Windows username contains spaces 🤷🏻‍♂️ 

**Info:**
```dart
SSHFS version 3.7.2
FUSE library version 3.10.4
using FUSE kernel interface version 7.31
fusermount3 version: 3.10.4


                   -`                    USER@arch-mi 
                  .o+`                   -------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: Mi NoteBook 14 
               `+oooooo:                 Kernel: 5.12.15-arch1-1 
               -+oooooo+:                Uptime: 39 mins 
             `/:-:++oooo+:               Packages: 880 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.8 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: GNOME 40.3 
         ./ooosssso++osssssso+`          WM: Mutter 
        .oossssso-````/ossssss+`         WM Theme: gnome-professional-40.1-dark 
       -osssssso.      :ssssssso.        Theme: gnome-professional-40.1-dark [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Tela-circle-blue-dark [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: gnome-terminal 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i5-10210U (8) @ 4.200GHz 
  `+sso+:-`                 `.-/+oso:    GPU: Intel CometLake-U GT2 [UHD Graphics] 
 `++:.                           `-/+/   Memory: 1913MiB / 7784MiB 
 .`                                 `/
```

```dart
        ,.=:!!t3Z3z.,                  USER@ZebWin-PC
       :tt:::tt333EE3                  --------------------------------
       Et:::ztt33EEEL @Ee.,      ..,   OS: Windows 11 Pro x86_64
      ;tt:::tt333EE7 ;EEEEEEttttt33#   Kernel: 10.0.21996
     :Et:::zt333EEQ. $EEEEEttttt33QL   Uptime: 2 hours, 46 mins
     it::::tt333EEF @EEEEEEttttt33F    Packages: 4 (scoop)
    ;3=*^```"*4EEV :EEEEEEttttt33@.    Shell: bash 4.4.23
    ,.=::::!t=., ` @EEEEEEtttz33QF     Resolution: 1920x1080
   ;::::::::zt33)   "4EEEtttji3P*      DE: Aero
  :t::::::::tt33.:Z3z..  `` ,..g.      WM: Explorer
  i::::::::zt33F AEEEtttt::::ztF       WM Theme: dark
 ;:::::::::t33V ;EEEttttt::::t3        Terminal: Windows Terminal
 E::::::::zt33L @EEEtttt::::z3F        CPU: Intel i5-3470S (4) @ 2.900GHz
{3=*^```"*4E3) ;EEEtttt:::::tZ`        Memory: 3521MiB / 8082MiB
             ` :EEEEtttt::::z7
                 "VEzjt:;;z>*`
```
