### ISSUE TITLE
How to integrate it with my current Cygwin installation, i.e., call sshfs from mintty.exe command line?

### ISSUE THREAD

**Issue by evandrocoan** [billziss-gh/sshfs-win#98]
Related question:
1. https://github.com/billziss-gh/sshfs-win/issues/3 question

I added it to Cygwin path with `PATH=$PATH:$(cygpath -u "C:\Program Files\SSHFS-Win\bin")` on `.bashrc` but it does not work when I try to use it:
```
Professional@PROFESSIONAL-PC$ sshfs -o allow_other,uid=197609 root@192.168.0.222:/ test/
missing host
see `/usr/bin/sshfs -h' for usage

Professional@PROFESSIONAL-PC$ sshfs
missing host
see `/usr/bin/sshfs -h' for usage

Professional@PROFESSIONAL-PC$ sshfs -h
missing host
see `/usr/bin/sshfs -h' for usage

Professional@PROFESSIONAL-PC$ /usr/bin/sshsf
bash: /usr/bin/sshsf: No such file or directory
```

I just keep saying `missing host` to all commands I try.

**Comment by billziss-gh** [comment]
You may have some luck with the following steps:

- Change to the `WinFsp/opt/cygfuse` directory and run `sh ./install.sh`. This installs "FUSE for Cygwin" into your Cygwin installation.
- Copy `sshfs.exe` into Cygwin's `/bin`.
- In this scenario no `PATH` modifications should be necessary.

**Comment by evandrocoan** [comment]
It worked! Thanks!!!!!!

My steps for future reference:
1. I removed the `PATH` entry I had added to `C:\Program Files\SSHFS-Win\bin`
1. I opened a `Cygwin mintty.exe` terminal on the directory `C:\Program Files (x86)\WinFsp\opt\cygfuse`
1. And run the command `bash install.sh`
   ```
   $ bash install.sh
   FUSE for Cygwin installed.
   ```
1. Copied the file `C:\Program Files\SSHFS-Win\bin\sshfs.exe` to Cygwin `/bin/`
1. Then, I closed my `Cygwin mintty.exe` terminal and opened a new fresh one.
1. Figured out which one is my `UID` with the command `echo $UID`
1. And I run the command `sshfs -o allow_other,uid=197609 root@192.168.0.222:/ ./remoteroot`

At first it did not worked because I had previously created the directory `./remoteroot` with `mkdir` as it is usually done on Linux systems. But it throwed the error: `Cannot create WinFsp-FUSE file system: mount point in use.` Then, I removed the directory `./remoteroot` and and I run the command again and it worked!

**Comment by evandrocoan** [comment]
Just one question, how can I umount it?

I tried:
```
$ fusermount -u  /cygdrive/d/User/Downloads/te
bash: fusermount: command not found

$ umount /cygdrive/d/User/Downloads/te
umount: /cygdrive/d/User/Downloads/te: Invalid argument

$ mount
F:/Cygwin/bin on /usr/bin type ntfs (binary,auto)
F:/Cygwin/lib on /usr/lib type ntfs (binary,auto)
F:/Cygwin on / type ntfs (binary,auto)
C: on /cygdrive/c type ntfs (binary,posix=0,user,noumount,auto)
D: on /cygdrive/d type ntfs (binary,posix=0,user,noumount,auto)
F: on /cygdrive/f type ntfs (binary,posix=0,user,noumount,auto)
```

**Comment by billziss-gh** [comment]
Glad to hear.

Regarding the "mount point in use" issue. There is an explanation for this behavior in the WinFsp FAQ:

https://github.com/billziss-gh/winfsp/wiki/Frequently-Asked-Questions#fuse

**Comment by billziss-gh** [comment]
> Just one question, how can I umount it?

FUSE for Cygwin does not integrate with Cygwin's mount functionality.

Simply kill the file system using `pkill sshfs`. This will actually correctly unmount the file system and free resources.

**Comment by evandrocoan** [comment]
Well, I just deleted the directory and it was gone at least.

**Comment by evandrocoan** [comment]
But the sshfs process still there:
```
$ ps aux | grep sshfs
     1757       1    1757       5988  ?         197609 16:01:15 /usr/bin/sshfs
```

**Comment by billziss-gh** [comment]
Kill the file system using `kill` or `pkill`.

**Comment by evandrocoan** [comment]
I installed the package `psmisc` with `apt-cyg install psmisc` and killed `sshfs` with `killall sshfs`

**Comment by DUOLabs333** [comment]
Is there  a way for me to use in Cygwin without it needing to be installed?
